import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Profile screen and its account modals (AddAccountModal,
// AccountDetailModal).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expense },
  errorDetail: { fontSize: 11.5, color: theme.colors.textSecondary, marginTop: 3, lineHeight: 16 },
  identity: { alignItems: 'center', paddingHorizontal: 20, paddingBottom: 8 },
  avatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: { fontFamily: theme.font.roundedBold, fontSize: 30 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  name: { fontFamily: theme.font.roundedBold, fontSize: 20, color: theme.colors.textPrimary },
  nameEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    marginTop: 12,
    marginHorizontal: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderRadius: theme.radius.lg,
    paddingHorizontal: 12,
  },
  nameInput: {
    flex: 1,
    paddingVertical: 10,
    fontFamily: theme.font.bodyMedium,
    fontSize: 15,
    color: theme.colors.textPrimary,
  },
  nameSave: { paddingLeft: 10 },
  memberSince: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 4 },

  netWorthCard: { marginHorizontal: 20, marginTop: 16, padding: 16 },
  netWorthLabel: {
    fontFamily: theme.font.bodyBold,
    fontSize: 10.5,
    color: theme.colors.textMuted,
    letterSpacing: 0.6,
  },
  // Profile's one hero number — the only place on this screen mono shows
  // up, matching the "rationed to one big figure per screen" rule.
  netWorthValue: {
    fontFamily: theme.font.monoBold,
    fontSize: 26,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },
  netWorthHint: { fontFamily: theme.font.body, fontSize: 11.5, color: theme.colors.textMuted, marginTop: 4 },

  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingHorizontal: 20, marginTop: 12 },
  statCell: {
    flexGrow: 1,
    flexBasis: '45%',
    padding: 14,
    borderRadius: theme.radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  statValue: { fontFamily: theme.font.roundedBold, fontSize: 18, color: theme.colors.onFlat },
  statLabel: {
    fontFamily: theme.font.bodyBold,
    fontSize: 10,
    color: theme.colors.onFlat,
    opacity: 0.65,
    marginTop: 2,
    letterSpacing: 0.6,
  },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 22,
    marginBottom: 4,
  },
  accountCardWrap: { marginHorizontal: 20, marginTop: 10 },
  accountCard: { padding: 16, borderRadius: 16 },
  accountCardInner: { flexDirection: 'row', alignItems: 'center' },
  accountName: { fontSize: 16, fontFamily: theme.font.bodyBold, color: theme.colors.onFlat },
  accountType: {
    fontSize: 12,
    color: theme.colors.onFlat,
    opacity: 0.6,
    marginTop: 2,
    textTransform: 'capitalize',
  },
  accountBalance: { fontSize: 16, fontFamily: theme.font.bodyBold, color: theme.colors.onFlat },
  negative: { color: theme.colors.expense },
  archivedCard: { opacity: 0.6 },

  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  hintText: { fontSize: 12, color: theme.colors.textMuted, marginBottom: 14, lineHeight: 17 },
  errorText: { color: theme.colors.expense, fontSize: 13, marginBottom: 12 },
  modalActions: { flexDirection: 'row', marginTop: 8 },
  dangerLabel: {
    fontSize: 11,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    letterSpacing: 0.5,
    marginTop: 20,
    marginBottom: 8,
  },
  deleteButton: { backgroundColor: theme.colors.expenseTint, borderColor: theme.colors.expense },
});
