import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW, SECTION_TITLE, SECTION_GAP } from '@/constants/textStyles';

// Shared by the Loans screen and every loan modal (LoanCard, LoanDetailModal, AssetModal, AccountModal,
// RateChangeModal, PrepayModal, AddLoanModal), so styling stays in one place.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginTop: theme.layout.screenTopGap,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expenseText },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },
  card: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 16,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  closedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 6,
  },
  closedDivider: EYEBROW,
  cardName: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 16,
    color: theme.colors.textPrimary,
    flexShrink: 1,
    marginRight: 8,
  },
  cardSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 4 },
  statLabel: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },
  errorText: { fontFamily: theme.font.body, color: theme.colors.expenseText, fontSize: 13, marginBottom: 12 },
  // The Overview / Schedule switch under a loan's card.
  sheetTabs: { marginBottom: 14 },
  sectionTitle: {
    ...SECTION_TITLE,
    marginTop: SECTION_GAP.top,
    marginBottom: SECTION_GAP.bottom,
  },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 4,
    marginBottom: 8,
    lineHeight: 17,
  },
  scheduleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderSoft,
  },
  rowLabel: { fontFamily: theme.font.bodyMedium, fontSize: 15, color: theme.colors.textPrimary },
  rowSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 2 },
  rowValue: { fontFamily: theme.font.monoBold, fontSize: 15, color: theme.colors.textPrimary },
  // A soft pill (the app's chip language) rather than grey capitals.
  statusTag: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    color: theme.colors.textSecondary,
    textTransform: 'capitalize',
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: theme.radius.pill,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 3,
  },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  wizardEyebrow: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    letterSpacing: 0.5,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
  progressRow: { flexDirection: 'row', gap: 5, marginBottom: 16 },
  progressSeg: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: theme.colors.surfaceAlt,
    overflow: 'hidden',
  },
  // Cross-faded in over the base segment above rather than swapped for it —
  // see AddLoanModal's own step2Fill comment.
  progressSegOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, borderRadius: 999 },
  endDateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  payoffCard: {
    marginBottom: 12,
    padding: 14,
    gap: 4,
    borderRadius: theme.radius.xl2,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  payoffMonth: { fontFamily: theme.font.roundedBold, fontSize: 22, color: theme.colors.textPrimary },
  payoffAxis: { flexDirection: 'row', justifyContent: 'space-between' },
});
