import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Loans screen and every loan modal (LoanCard, LoanDetailModal,
// AssetModal, AccountModal, RateChangeModal, PrepayModal, AddLoanModal) so the
// styling stays in one place instead of a 2000-line screen file.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  sectionSwitch: { paddingHorizontal: 20 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expense },
  errorDetail: { fontSize: 11.5, color: theme.colors.textSecondary, marginTop: 3, lineHeight: 16 },
  sectionHeading: { fontFamily: theme.font.roundedBold, fontSize: 16, color: theme.colors.textPrimary },
  summaryRow: { flexDirection: 'row', paddingHorizontal: 20, gap: 10, marginBottom: 16 },
  summaryCard: { flex: 1, padding: 14 },
  summaryIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  summaryIconExpense: { backgroundColor: theme.colors.expenseTint },
  summaryIconIncome: { backgroundColor: theme.colors.incomeTint },
  summaryLabel: { fontSize: 12, color: theme.colors.textMuted, marginBottom: 4 },
  summaryValue: { fontSize: 17, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  summaryValueExpense: { color: theme.colors.expense },
  summaryValueIncome: { color: theme.colors.income },
  emptyText: { marginHorizontal: 20, color: theme.colors.textMuted, fontSize: 13 },
  card: {
    marginHorizontal: 20,
    marginBottom: 10,
    padding: 16,
    borderRadius: 12,
  },
  // Direction reads as a slim rail, not a full-bleed wash — the same
  // red/green the rest of the app already uses for money out vs in, applied
  // as one accent line rather than tinting the whole card.
  cardRailBorrowed: { borderLeftWidth: 3, borderLeftColor: theme.colors.expense },
  cardRailLent: { borderLeftWidth: 3, borderLeftColor: theme.colors.income },
  cardMuted: { opacity: 0.6 },
  closedDivider: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    color: theme.colors.textMuted,
    letterSpacing: 0.6,
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 6,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardName: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    flexShrink: 1,
    marginRight: 8,
  },
  cardSub: { fontSize: 12, color: theme.colors.textMuted, marginTop: 4 },
  cardStatsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  infoGrid: { flexDirection: 'row', gap: 10, marginTop: 12 },
  infoBox: {
    flex: 1,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderRadius: theme.radius.md,
    padding: 10,
  },
  statLabel: { fontSize: 11, color: theme.colors.textMuted },
  statValue: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary, marginTop: 2 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  badgeExpense: { backgroundColor: theme.colors.expenseTint },
  badgeIncome: { backgroundColor: theme.colors.incomeTint },
  badgeText: { fontSize: 11, fontWeight: '600', color: theme.colors.textPrimary },
  // Status as a small bordered pill rather than tinting the whole card — the
  // loan's own numbers stay the visually loudest thing on the tile.
  // A neutral pill with just a colored dot, not a second fill color — the
  // card itself is already colored by direction, so a loudly-tinted status
  // badge on top of that would be two colors competing on one small tile.
  statusPill: {
    alignSelf: 'flex-start',
    marginTop: 2,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: theme.colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  statusPillActive: {},
  statusPillClosed: { opacity: 0.7 },
  statusPillDefaulted: {},
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusDotActive: { backgroundColor: theme.colors.income },
  statusDotClosed: { backgroundColor: theme.colors.textMuted },
  statusDotDefaulted: { backgroundColor: theme.colors.gold },
  statusPillText: {
    fontSize: 10,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textPrimary,
    textTransform: 'capitalize',
  },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  modalSheet: {
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '88%',
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: theme.colors.textPrimary, marginBottom: 16 },
  emiPreview: { borderRadius: 10, padding: 14, marginBottom: 14, borderWidth: theme.border.thin },
  emiPreviewLabel: { fontSize: 12, color: theme.colors.primary, fontWeight: '600' },
  emiPreviewValue: { fontSize: 20, fontWeight: '700', color: theme.colors.primary, marginTop: 2 },
  errorText: { color: theme.colors.expense, fontSize: 13, marginBottom: 12 },
  modalActions: { flexDirection: 'row', marginTop: 8 },
  deleteButton: { backgroundColor: theme.colors.expenseTint, borderColor: theme.colors.expense },
  detailHero: { padding: 15, marginTop: 4 },
  detailHeroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  kebabBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewAllText: { fontSize: 13, fontWeight: '700', color: theme.colors.textSecondary, textAlign: 'center' },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    marginTop: 20,
    marginBottom: 8,
  },
  hintText: { fontSize: 12, color: theme.colors.textMuted, marginTop: 4, marginBottom: 8, lineHeight: 17 },
  scheduleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  rowLabel: { fontSize: 14, color: theme.colors.textPrimary, fontWeight: '500' },
  rowSub: { fontSize: 11, color: theme.colors.textMuted, marginTop: 2 },
  rowValue: { fontSize: 14, color: theme.colors.textPrimary, fontWeight: '600' },
  assetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    padding: 12,
    borderRadius: theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  income: { color: theme.colors.income },
  expense: { color: theme.colors.expense },
  statusTag: {
    fontSize: 10,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    marginTop: 2,
    fontWeight: '700',
  },
  statusTagPaid: { color: theme.colors.income },
  confirmSheet: {
    backgroundColor: theme.colors.background,
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 24,
    alignSelf: 'center',
    width: '90%',
  },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  wizardEyebrow: {
    fontSize: 10.5,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
  progressRow: { flexDirection: 'row', gap: 5, marginBottom: 16 },
  progressSeg: { flex: 1, height: 4, borderRadius: 999, backgroundColor: theme.colors.surfaceAlt },
  progressSegDone: { backgroundColor: theme.colors.primary },
  endDateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  dateFieldsRow: { flexDirection: 'row', gap: 10 },
  dateFieldInput: { flex: 1, textAlign: 'center' },
});
