import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Loans screen and every loan modal (LoanCard, LoanDetailModal,
// AssetModal, AccountModal, RateChangeModal, PrepayModal, AddLoanModal) so the
// styling stays in one place instead of a 2000-line screen file.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  // Shown only before the first successful load, same gate as Transactions/
  // Reports — see the note on `loaded` in loans.tsx.
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  sectionSwitch: { paddingHorizontal: 20 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expense },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },
  sectionHeading: { fontFamily: theme.font.roundedBold, fontSize: 16, color: theme.colors.textPrimary },
  // Plain stats, not flat-coloured cards — matches Transactions' own
  // headline treatment (one confident figure, no colour blocking) rather
  // than two boxed tiles competing with the loan list below them.
  summaryRow: { flexDirection: 'row', paddingHorizontal: 20, gap: 28, marginBottom: 18 },
  summaryText: { flex: 1, minWidth: 0 },
  summaryLabel: {
    fontFamily: theme.font.mono,
    fontSize: 9,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
  },
  summaryValue: {
    fontSize: 22,
    fontFamily: theme.font.monoBold,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },
  summaryValueExpense: { color: theme.colors.expense },
  summaryValueIncome: { color: theme.colors.income },
  card: {
    marginHorizontal: 20,
    marginBottom: 10,
    padding: 16,
    borderRadius: theme.radius.xl2,
  },
  // Direction reads as a slim rail, not a full-bleed wash — the same
  // red/green the rest of the app already uses for money out vs in, applied
  // as one accent line rather than tinting the whole card.
  cardRailBorrowed: { borderLeftWidth: 3, borderLeftColor: theme.colors.expense },
  cardRailLent: { borderLeftWidth: 3, borderLeftColor: theme.colors.income },
  cardMuted: { opacity: 0.6 },
  closedDivider: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    color: theme.colors.textMuted,
    letterSpacing: 0.6,
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 6,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  // Payoff-first list row: outstanding/EMI stay top-right same as before,
  // but the direction rail and status-dot pill are gone in favour of one
  // thin progress bar — see LoanCard's own comment and payoffFraction().
  loanFigs: { alignItems: 'flex-end', flexShrink: 0, marginLeft: 8 },
  loanOutstanding: { fontSize: 16, fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  loanEmi: { fontFamily: theme.font.body, fontSize: 10.5, color: theme.colors.textMuted, marginTop: 1 },
  payoffTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.surfaceAlt,
    marginTop: 12,
    overflow: 'hidden',
  },
  payoffFill: { height: '100%', borderRadius: 3 },
  payoffFillBorrowed: { backgroundColor: theme.colors.expense },
  payoffFillLent: { backgroundColor: theme.colors.income },
  payoffFillClosed: { backgroundColor: theme.colors.textMuted },
  payoffCaption: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  payoffCaptionText: { fontFamily: theme.font.mono, fontSize: 9.5, color: theme.colors.textMuted },
  payoffCaptionBold: { fontFamily: theme.font.monoBold, color: theme.colors.textSecondary },
  cardName: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 16,
    color: theme.colors.textPrimary,
    flexShrink: 1,
    marginRight: 8,
  },
  cardSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 4 },
  cardStatsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  statLabel: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },
  statValue: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary, marginTop: 2 },
  emiPreview: { borderRadius: 10, padding: 14, marginBottom: 14, borderWidth: theme.border.thin },
  emiPreviewLabel: { fontFamily: theme.font.bodyMedium, fontSize: 12, color: theme.colors.primary },
  emiPreviewValue: {
    fontFamily: theme.font.bodyBold,
    fontSize: 20,
    color: theme.colors.primary,
    marginTop: 2,
  },
  errorText: { fontFamily: theme.font.body, color: theme.colors.expense, fontSize: 13, marginBottom: 12 },
  detailHero: { padding: 15, marginTop: 4 },
  detailHeroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  kebabBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewAllText: {
    fontFamily: theme.font.bodyBold,
    fontSize: 13,
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
  sectionTitle: {
    fontFamily: theme.font.roundedBold,
    fontSize: 16,
    color: theme.colors.textPrimary,
    marginTop: 20,
    marginBottom: 8,
  },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 4,
    marginBottom: 8,
    lineHeight: 17,
  },
  scheduleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  rowLabel: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.textPrimary },
  rowSub: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted, marginTop: 2 },
  rowValue: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.textPrimary },
  assetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    padding: 12,
    borderRadius: theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  income: { color: theme.colors.income },
  expense: { color: theme.colors.expense },
  // A soft pill (the app's chip language) rather than grey capitals.
  statusTag: {
    fontFamily: theme.font.bodyBold,
    fontSize: 10.5,
    color: theme.colors.textSecondary,
    textTransform: 'capitalize',
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: theme.radius.pill,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 3,
  },
  statusTagPaid: { color: theme.colors.income, backgroundColor: theme.colors.incomeTint },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  wizardEyebrow: {
    fontFamily: theme.font.bodyBold,
    fontSize: 10.5,
    letterSpacing: 0.5,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
  progressRow: { flexDirection: 'row', gap: 5, marginBottom: 16 },
  progressSeg: {
    flex: 1,
    height: 4,
    borderRadius: 999,
    backgroundColor: theme.colors.surfaceAlt,
    overflow: 'hidden',
  },
  progressSegDone: { backgroundColor: theme.colors.primary },
  // Cross-faded in over the base segment above rather than swapped for it —
  // see AddLoanModal's own step2Fill comment.
  progressSegOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, borderRadius: 999 },
  endDateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  dateFieldsRow: { flexDirection: 'row', gap: 10 },
  dateFieldInput: { flex: 1, textAlign: 'center' },
});
