import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

export const styles = StyleSheet.create({
  card: { marginHorizontal: 20, marginTop: 4, overflow: 'hidden' },
  inner: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 16 },
  bar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  title: { fontFamily: theme.font.roundedBold, fontSize: 16, color: theme.colors.textPrimary },
  nav: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  navBtn: {
    width: 32,
    height: 32,
    borderRadius: theme.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.tray,
  },
  navBtnOff: { opacity: 0.35 },
  body: { marginTop: 12 },

  top: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  headline: { flex: 1, minWidth: 0 },
  headLabel: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  headValue: {
    fontFamily: theme.font.monoBold,
    fontSize: 38,
    lineHeight: 44,
    letterSpacing: -1.5,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },
  headSymbol: {
    fontFamily: theme.font.monoBold,
    fontSize: 22,
    letterSpacing: 0,
    color: theme.colors.textMuted,
  },
  headValueNeg: { color: theme.colors.expenseText },
  headCaption: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 19,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  dueChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
    marginTop: 12,
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.dueTint,
  },
  dueDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: theme.colors.slice.due },
  dueText: { flexShrink: 1, fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.dueInk },
  dueMoney: { fontFamily: theme.font.monoBold, fontSize: 13 },
  working: {
    marginTop: 12,
    borderRadius: 16,
    backgroundColor: theme.colors.tray,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  workingRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 5,
  },
  workingTotal: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    marginTop: 3,
    paddingTop: 8,
  },
  workingLabel: { flex: 1, fontFamily: theme.font.body, fontSize: 14, color: theme.colors.textSecondary },
  workingLabelTotal: { fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  workingValue: { fontFamily: theme.font.monoBold, fontSize: 14, color: theme.colors.textPrimary },
  workingValueDue: { color: theme.colors.dueInk },

  // Spent | Saved | Debt left: one row on the card, split by faint dividers.
  legend: {
    flexDirection: 'row',
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  legendItem: { flex: 1, minWidth: 0, minHeight: 48, justifyContent: 'center', borderRadius: 12 },
  legendDivider: { paddingLeft: 12, borderLeftWidth: 1, borderLeftColor: theme.colors.divider },
  legendActive: { backgroundColor: theme.colors.tray },
  legendFaded: { opacity: 0.4 },
  legendHead: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendLabel: {
    flexShrink: 1,
    fontFamily: theme.font.bodyMedium,
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  legendValue: {
    fontFamily: theme.font.monoBold,
    fontSize: 15,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },

  // Today and pace, together in one quiet tray under the legend.
  tray: {
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
    borderRadius: 16,
    backgroundColor: theme.colors.tray,
  },
  line: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  lineLabel: { flex: 1, fontFamily: theme.font.body, fontSize: 14, color: theme.colors.textSecondary },
  lineMoney: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  todayMeter: { width: 84 },

  // Suu's line: the card's pale-secondary footer, set inline (coral when Suu is worried), with Suu's own mark.
  suu: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  suuWarn: { backgroundColor: theme.colors.idCoral },
  suuText: {
    flex: 1,
    fontFamily: theme.font.roundedMedium,
    fontSize: 14.5,
    lineHeight: 20,
    color: '#1C5A43',
  },
  suuTextWarn: { color: theme.colors.expenseText },

  confettiDot: {
    position: 'absolute',
    top: 4,
    left: '50%',
    width: 5,
    height: 5,
    borderRadius: 1,
    marginLeft: -2.5,
  },
});
