import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Categories screen, its list section (CategorySection /
// CategoryTile / SubcategoryPill) and AddCategoryModal.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  sectionTitle: {
    fontSize: 12,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 16, gap: 12, marginBottom: 4 },
  groupCard: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.border,
  },
  groupCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  groupCardTitle: {
    flex: 1,
    fontSize: 14.5,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textPrimary,
  },
  groupCardCount: { fontSize: 11.5, color: theme.colors.textMuted },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.border,
  },
  pillDot: { width: 8, height: 8, borderRadius: 4 },
  pillText: { fontSize: 12.5, fontFamily: theme.font.bodyMedium, color: theme.colors.textPrimary },
  hintText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginHorizontal: 20,
    marginTop: 14,
    lineHeight: 17,
  },
  modalHint: { fontSize: 12, color: theme.colors.textMuted, marginBottom: 14, lineHeight: 17 },
  sensitiveRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  errorText: { color: theme.colors.expense, fontSize: 13, marginBottom: 12 },
  tile: { width: 76, alignItems: 'center' },
  tileSub: { width: 68, opacity: 0.88 },
  tileName: {
    fontSize: 11,
    color: theme.colors.textPrimary,
    fontFamily: theme.font.bodyMedium,
    marginTop: 6,
    textAlign: 'center',
  },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: theme.colors.textPrimary, marginBottom: 16 },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  colorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  colorSwatch: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.ink,
  },
  colorSwatchActive: { borderWidth: 3, borderColor: theme.colors.textPrimary },
  parentChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  parentChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  parentChipText: { fontSize: 12.5, fontFamily: theme.font.bodyMedium, color: theme.colors.textPrimary },
  parentChipTextActive: { color: theme.colors.white },
  modalActions: { flexDirection: 'row', marginTop: 8 },
});
