import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { listScreenStyles } from '@/features/shared/listScreenStyles';
import { SECTION_TITLE, SECTION_GAP } from '@/constants/textStyles';

/** Tiles per row on the Categories grid (a cell is one column wide). */
export const TILE_COLUMNS = 4;

// Shared by the Categories screen, its list section (CategorySection /
// CategoryTile / SubcategoryPill) and AddCategoryModal.
export const styles = StyleSheet.create({
  ...listScreenStyles,
  sectionTitle: {
    ...SECTION_TITLE,
    marginHorizontal: 20,
    marginTop: SECTION_GAP.top,
    marginBottom: SECTION_GAP.bottom,
  },
  firstTitle: { marginTop: theme.layout.screenTopGap },
  grid: { paddingHorizontal: 18, gap: 12, marginBottom: 4 },
  gridRow: { flexDirection: 'row' },
  cell: { width: `${100 / TILE_COLUMNS}%`, paddingHorizontal: 2 },
  panelWrap: { marginTop: 10 },
  notch: {
    position: 'absolute',
    top: -6,
    width: 12,
    height: 12,
    marginLeft: -6,
    backgroundColor: theme.colors.surface,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    transform: [{ rotate: '45deg' }],
  },
  panel: {
    marginHorizontal: 6,
    padding: 14,
    borderRadius: theme.radius.xl2,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  panelHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  panelTitle: { flex: 1, ...SECTION_TITLE, fontFamily: theme.font.roundedBold, fontSize: 15 },
  panelCount: { fontFamily: theme.font.body, fontSize: 11.5, color: theme.colors.textMuted },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: theme.colors.surfaceAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  pillDot: { width: 8, height: 8, borderRadius: 4 },
  pillText: { fontSize: 12.5, fontFamily: theme.font.bodyMedium, color: theme.colors.textPrimary },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginHorizontal: 20,
    marginTop: 14,
    lineHeight: 17,
  },
  sensitiveRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  tile: { alignItems: 'center' },
  tileRing: { padding: 2, borderWidth: 2, borderColor: 'transparent', borderRadius: 20 },
  tileRingOn: { borderColor: theme.colors.ink },
  tileBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.ink,
  },
  tileBadgeText: {
    fontFamily: theme.font.bodyBold,
    fontSize: 10,
    lineHeight: 13,
    color: theme.colors.surface,
  },
  tileName: {
    fontSize: 11.5,
    lineHeight: 14,
    color: theme.colors.textPrimary,
    fontFamily: theme.font.bodyMedium,
    marginTop: 4,
    textAlign: 'center',
  },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  iconChoice: {
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  iconChoiceActive: { borderWidth: 2, borderColor: theme.colors.ink },
  colorRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  colorSwatch: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.inkHairline,
  },
  colorSwatchActive: { borderWidth: 2.5, borderColor: theme.colors.ink },
  parentChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  parentChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  parentChipText: { fontSize: 12.5, fontFamily: theme.font.bodyMedium, color: theme.colors.textPrimary },
  parentChipTextActive: { color: theme.colors.white },
});
