import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Friends & Family screen, PersonRow, and the person modals.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expense },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },
  emptyText: {
    fontFamily: theme.font.body,
    marginHorizontal: 20,
    color: theme.colors.textMuted,
    fontSize: 13,
  },
  // Each person's own tile — same spacing/radius as a LoanCard.
  card: { marginHorizontal: 20, marginBottom: 10, padding: 16, borderRadius: theme.radius.xl2 },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  who: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 0, marginRight: 8 },
  cardName: {
    fontFamily: theme.font.roundedMedium,
    fontSize: 15,
    color: theme.colors.textPrimary,
    marginLeft: 12,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    borderRadius: theme.radius.pill,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 4,
    marginLeft: 12,
  },
  statusDot: { width: 5, height: 5, borderRadius: 2.5 },
  statusPillText: { fontFamily: theme.font.bodyBold, fontSize: 9.5 },
  cardRight: { alignItems: 'flex-end', flexShrink: 0 },
  cardBalance: { fontSize: 16, fontFamily: theme.font.monoBold },
  cardSub: { fontFamily: theme.font.body, fontSize: 9.5, color: theme.colors.textMuted, marginTop: 2 },
  skeletonCard: {
    backgroundColor: theme.colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  // The detail sheet's linked-loan and history rows: a plain divided list
  // suits a modal's inner list better than more tiles.
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  rowLabel: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.textPrimary },
  rowSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 2 },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: { fontFamily: theme.font.bodyBold, fontSize: 15, color: theme.colors.onFlat },
  rowValue: { fontFamily: theme.font.monoBold, fontSize: 13.5 },
  detailBalance: { fontFamily: theme.font.monoBold, fontSize: 20, marginBottom: 16 },
  sectionTitle: {
    fontFamily: theme.font.roundedBold,
    fontSize: 16,
    color: theme.colors.textPrimary,
    marginTop: 20,
    marginBottom: 4,
  },
  fieldLabel: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 6,
    marginTop: 4,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  dateFieldsRow: { flexDirection: 'row', gap: 10 },
  dateFieldInput: { flex: 1, textAlign: 'center' },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginBottom: 10,
    lineHeight: 17,
  },
  errorText: { fontFamily: theme.font.bodyBold, color: theme.colors.expense, fontSize: 13, marginBottom: 10 },
  historyIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
});
