import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { SECTION_TITLE, SECTION_GAP, EYEBROW } from '@/constants/textStyles';

// Shared by the Friends & Family screen, PersonTile, and the person modals.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginTop: theme.layout.screenTopGap,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expenseText },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },
  emptyText: {
    fontFamily: theme.font.body,
    marginHorizontal: 20,
    color: theme.colors.textMuted,
    fontSize: 13,
  },
  // A row of person tiles (one or two across) and the headings that group them.
  groupHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginHorizontal: 24,
    marginTop: 14,
    marginBottom: 8,
  },
  groupTitle: EYEBROW,
  groupTotal: { fontFamily: theme.font.monoBold, fontSize: 12 },
  tileRow: { flexDirection: 'row', gap: 10, marginHorizontal: 20, marginBottom: 10 },
  tileCell: { flex: 1, minWidth: 0 },
  personTile: {
    padding: 14,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  tileWho: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  tileAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.inkHairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileInitial: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.onFlat },
  tileName: {
    flex: 1,
    minWidth: 0,
    fontFamily: theme.font.roundedMedium,
    fontSize: 15,
    color: theme.colors.textPrimary,
  },
  tileAmount: { fontFamily: theme.font.monoBold, fontSize: 18, marginTop: 12 },
  tileMeta: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textSecondary, marginTop: 2 },
  settlePill: {
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingHorizontal: 13,
    paddingVertical: 6,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.glass,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.inkHairline,
  },
  settlePillText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textPrimary },
  settledTitle: { ...EYEBROW, marginHorizontal: 24, marginTop: 8, marginBottom: 2 },
  quietRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 20,
    paddingHorizontal: 4,
    paddingVertical: 10,
  },
  quietAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quietInitial: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.onFlat },
  quietName: {
    flex: 1,
    minWidth: 0,
    fontFamily: theme.font.roundedMedium,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  quietSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted },
  skeletonTile: { backgroundColor: theme.colors.surface },
  // The detail sheet's linked-loan and history rows: a plain divided list
  // suits a modal's inner list better than more tiles.
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.borderSoft,
  },
  moreBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  rowLabel: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.textPrimary },
  rowSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 2 },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: { fontFamily: theme.font.bodyBold, fontSize: 15, color: theme.colors.onFlat },
  rowValue: { fontFamily: theme.font.monoBold, fontSize: 13.5 },
  // The Settle / History switch under a person's card.
  sheetTabs: { marginBottom: 14 },
  sectionTitle: {
    ...SECTION_TITLE,
    marginTop: SECTION_GAP.top,
    marginBottom: SECTION_GAP.bottom,
  },
  fieldLabel: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 6,
    marginTop: 4,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginBottom: 10,
    lineHeight: 17,
  },
  errorText: {
    fontFamily: theme.font.bodyBold,
    color: theme.colors.expenseText,
    fontSize: 13,
    marginBottom: 12,
  },
  historyIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
});
