import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { SECTION_TITLE, SECTION_GAP } from '@/constants/textStyles';
import { SCREEN } from '@/components/screenStyles';
import { GLASS } from '@/components/Glass';

/** The even gap between Reports' blocks (heatmap card, day card, story cards, "Where it went"). */
export const BLOCK_GAP = SCREEN.sectionGap;

// Shared by the Reports screen and its pieces (PeriodRow, HeatmapCard, DayCard, StoryCards, CategoryBar, CategoryList, TrendChart, DayTotal).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  errTitle: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.expenseText },
  errDetail: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginTop: 4,
    textAlign: 'center',
  },
  errRetry: { marginTop: 16, alignSelf: 'stretch' },
  empty: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textMuted, marginVertical: 16 },

  periodRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  periodPill: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: GLASS.edge,
    backgroundColor: GLASS.fillStrong,
    borderRadius: theme.radius.pill,
  },
  periodArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  periodArrowOff: { opacity: 0.35 },
  // Shrinks and wraps rather than clipping a long custom range ("20 Dec 2025 – 4 Jan 2026").
  periodLabel: {
    flexShrink: 1,
    textAlign: 'center',
    fontFamily: theme.font.roundedBold,
    fontSize: 17,
    color: theme.colors.textPrimary,
  },
  granChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 48,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: GLASS.edge,
    backgroundColor: GLASS.fillStrong,
    borderRadius: theme.radius.pill,
  },
  granChipText: { fontFamily: theme.font.roundedMedium, fontSize: 15, color: theme.colors.ink },
  // Days / Categories / Trends, pinned under the header. SegmentedControl
  // brings its own bottom margin; the negative one trims it to the gap this bar wants.
  // On the page colour, so the report scrolls under the tabs once they stick.
  tabs: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  stickyTabs: { marginHorizontal: -20, zIndex: 1 },

  // The Days tab's heatmap card.
  hmCard: {
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 14,
    gap: 12,
    marginBottom: BLOCK_GAP,
    boxShadow: GLASS.shadow,
  },
  hmHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 2,
  },
  hmTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  filterChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: '100%',
    borderRadius: theme.radius.pill,
    backgroundColor: 'rgba(255,255,255,0.7)',
    minHeight: 32,
    paddingLeft: 12,
    paddingRight: 10,
  },
  filterChipText: {
    flexShrink: 1,
    fontFamily: theme.font.bodyBold,
    fontSize: 13,
    color: theme.colors.textPrimary,
  },
  hmHint: {
    paddingHorizontal: 2,
    fontFamily: theme.font.body,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },

  // Story cards: the period "in short", swiped sideways.
  storyBlock: { marginBottom: BLOCK_GAP },
  storyHead: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between' },
  storyPos: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textMuted },
  story: {
    minHeight: 176,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: GLASS.edge,
    boxShadow: GLASS.shadow,
    padding: 18,
    justifyContent: 'space-between',
    gap: 10,
  },
  storyCompact: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 3,
  },
  storyCompactTitle: { fontFamily: theme.font.bodyBold, fontSize: 15, color: theme.colors.textPrimary },
  storyCompactDetail: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textSecondary,
  },
  storyKicker: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textSecondary },
  storyBig: {
    fontFamily: theme.font.roundedBold,
    fontSize: 30,
    lineHeight: 34,
    color: theme.colors.textPrimary,
  },
  storyDetail: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textPrimary,
    marginTop: 6,
  },
  storyCta: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.textPrimary },
  storyFoot: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textSecondary },
  storyMoonRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  storyMoonText: { flex: 1, minWidth: 0 },
  storyDots: { flexDirection: 'row', justifyContent: 'center', gap: 6, marginTop: 12 },
  storyDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#DCD3C1' },
  storyDotOn: { width: 18, backgroundColor: theme.colors.ink },

  // The day open under the heatmap.
  dayCard: {
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    paddingTop: 14,
    paddingBottom: 12,
    marginBottom: BLOCK_GAP,
    boxShadow: GLASS.shadow,
  },
  dayHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  dayHeadText: { flex: 1, minWidth: 0 },
  dayTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  dayClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  dayFoot: {
    marginTop: 4,
    paddingTop: 10,
    paddingHorizontal: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },

  // Weekday rhythm: seven bars, a dashed "usual day" line, and a read line.
  rhythmBlock: { marginBottom: BLOCK_GAP },
  rhythmCard: {
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    padding: 16,
    gap: 12,
    boxShadow: GLASS.shadow,
  },
  rhythmChart: { height: 140, flexDirection: 'row', alignItems: 'flex-end', gap: 8, paddingTop: 16 },
  rhythmBar: { flex: 1, height: '100%', justifyContent: 'flex-end', alignItems: 'center', gap: 4 },
  rhythmValue: {
    minHeight: 15,
    fontFamily: theme.font.mono,
    fontSize: 11,
    color: theme.colors.textMuted,
  },
  rhythmValueOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  rhythmFill: { width: '100%', borderTopLeftRadius: 8, borderTopRightRadius: 8, borderRadius: 4 },
  rhythmLabel: { minHeight: 16, fontFamily: theme.font.mono, fontSize: 12, color: theme.colors.textMuted },
  rhythmLabelOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  rhythmUsual: {
    position: 'absolute',
    left: 0,
    right: 0,
    borderTopWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.colors.textSecondary,
    opacity: 0.55,
  },
  rhythmUsualTag: {
    position: 'absolute',
    right: 0,
    bottom: 2,
    paddingHorizontal: 4,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.85)',
    fontFamily: theme.font.mono,
    fontSize: 11,
    color: theme.colors.textSecondary,
  },
  rhythmRead: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textPrimary,
  },
  rhythmEmpty: {
    paddingVertical: 18,
    paddingHorizontal: 14,
    textAlign: 'center',
    fontFamily: theme.font.body,
    fontSize: 14,
    color: theme.colors.textMuted,
  },

  // Biggest spends: the period's largest single expenses, in the day card's row.
  bigBlock: { marginBottom: BLOCK_GAP },
  bigCard: {
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    paddingTop: 4,
    paddingBottom: 12,
    overflow: 'hidden',
    boxShadow: GLASS.shadow,
  },
  bigFoot: {
    marginTop: 4,
    paddingTop: 12,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
    fontFamily: theme.font.body,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  bigFootStrong: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  bigRowOn: { backgroundColor: 'rgba(18,19,15,0.05)' },

  // Categories: how the list is grouped (by category or by account).
  catSplitCaption: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textMuted,
    paddingTop: 8,
  },

  // Trends: one line chart with a Spending / Net worth switch.
  trendCard: {
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    padding: 16,
    gap: 8,
    boxShadow: GLASS.shadow,
  },
  trendHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  trendTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  trendSwitch: {
    flexDirection: 'row',
    padding: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  trendSwitchBtn: {
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
  },
  trendSwitchBtnOn: { backgroundColor: theme.colors.ink },
  trendSwitchText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textSecondary },
  trendSwitchTextOn: { fontFamily: theme.font.bodyBold, color: theme.colors.surface },
  trendRead: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textSecondary,
  },

  trendBlock: { marginTop: BLOCK_GAP, gap: 12 },

  // Money in and out: paired bars per month with what was kept under each, then a three-cell summary.
  flowLegend: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  flowLegendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  flowLegendDot: { width: 10, height: 10, borderRadius: 3 },
  flowLegendText: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textSecondary },
  flowChart: { flexDirection: 'row', alignItems: 'flex-end', gap: 2, paddingTop: 6 },
  flowCol: { flex: 1, alignItems: 'center', gap: 6, paddingTop: 6, paddingBottom: 6, borderRadius: 12 },
  flowColOn: { backgroundColor: theme.colors.inkWash },
  flowBars: { height: 100, flexDirection: 'row', alignItems: 'flex-end', gap: 2 },
  flowBar: { width: 10, borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  flowBarEdge: {
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: theme.colors.textMuted,
  },
  flowBarLive: { borderWidth: 1.5, borderStyle: 'dashed', borderColor: theme.colors.ink },
  flowLabel: { fontFamily: theme.font.mono, fontSize: 12, color: theme.colors.textMuted },
  flowLabelOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  flowKept: {
    minWidth: 38,
    alignItems: 'center',
    paddingVertical: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.secondaryTint,
  },
  flowKeptNeg: { backgroundColor: theme.colors.idCoral },
  flowKeptLive: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: theme.colors.secondaryDeep,
  },
  flowKeptText: { fontFamily: theme.font.monoBold, fontSize: 11, color: theme.colors.incomeText },
  flowKeptTextNeg: { color: theme.colors.expenseText },
  flowKeptCaption: {
    textAlign: 'center',
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  stripCard: {
    flexDirection: 'row',
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    boxShadow: GLASS.shadow,
  },
  stripCardStack: { flexDirection: 'column' },
  stripCell: { flex: 1, minWidth: 0, paddingHorizontal: 14, paddingVertical: 14, gap: 3 },
  stripCellStacked: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.borderSoft },
  stripCellDivided: { borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: theme.colors.borderSoft },
  stripLabel: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textSecondary },
  stripValue: { fontFamily: theme.font.monoBold, fontSize: 16, color: theme.colors.textPrimary },
  stripSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted },

  // Against your usual: each category's month beside its own earlier months.
  tracksBlock: { marginTop: BLOCK_GAP },
  tracksCard: {
    backgroundColor: GLASS.fill,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS.edge,
    overflow: 'hidden',
    boxShadow: GLASS.shadow,
  },
  trackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 68,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  trackMid: { flex: 1, minWidth: 0 },
  trackName: { fontFamily: theme.font.bodyBold, fontSize: 15, color: theme.colors.textPrimary },
  trackSub: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textMuted, marginTop: 2 },
  trackEnd: { alignItems: 'flex-end', gap: 4 },
  trackPct: { fontFamily: theme.font.monoBold, fontSize: 12, color: theme.colors.textMuted },
  trackPctOver: { color: theme.colors.expenseText },
  trackPctUnder: { color: theme.colors.incomeText },
  trackFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  trackFootText: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textMuted },
  trackFootLink: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.link },
  tracksNote: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textMuted, marginTop: 8 },

  trendLink: { alignSelf: 'flex-start', paddingVertical: 8 },
  trendLinkText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.link },

  tidyNudge: {
    marginTop: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: theme.colors.dueTint,
  },
  tidyNudgeText: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textPrimary,
  },
  tidyNudgeLink: { fontFamily: theme.font.bodyBold, textDecorationLine: 'underline' },
  blockTitle: { ...SECTION_TITLE, marginBottom: SECTION_GAP.bottom },
  legend: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendText: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },
  legendSwatch: { width: 12, height: 12, borderRadius: 4 },

  catCard: {
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
    borderRadius: 24,
    paddingHorizontal: 16,
    overflow: 'hidden',
    boxShadow: GLASS.shadow,
  },
  catBar: {
    flexDirection: 'row',
    height: 16,
    gap: 3,
    marginTop: 4,
    marginBottom: 14,
    borderRadius: 8,
    overflow: 'hidden',
  },
  catBarSeg: { flexBasis: 0, minWidth: 3, borderRadius: 4 },
  catRow: { paddingVertical: 12 },
  // The picked row: tinted edge to edge, the others fade.
  catRowOn: { marginHorizontal: -16, paddingHorizontal: 16, backgroundColor: theme.colors.tray },
  catRowDim: { opacity: 0.5 },
  catPanel: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 4,
    backgroundColor: theme.colors.tray,
  },
  catSplitLoading: { paddingVertical: 8 },
  catSplitRow: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 30, paddingLeft: 18 },
  catSplitName: { flex: 1, fontFamily: theme.font.body, fontSize: 14, color: theme.colors.textSecondary },
  catSplitAmt: { fontFamily: theme.font.mono, fontSize: 14, color: theme.colors.textPrimary },
  catLinks: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 18, rowGap: 2, paddingTop: 4 },
  catLink: { paddingVertical: 8 },
  catLinkText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.link },
  catTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  catName: { flex: 1, fontFamily: theme.font.bodyBold, fontSize: 15, color: theme.colors.textPrimary },
  catDot: { width: 10, height: 10, borderRadius: 5 },
  catPct: {
    fontFamily: theme.font.mono,
    fontSize: 12,
    color: theme.colors.textMuted,
    width: 38,
    textAlign: 'right',
  },
  catRight: { flexDirection: 'row', alignItems: 'center', gap: 6, marginLeft: 8 },
  catAmt: { fontFamily: theme.font.monoBold, fontSize: 15, color: theme.colors.textPrimary },
  catDelta: { fontFamily: theme.font.monoBold, fontSize: 12 },
  catTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.inkWash,
    overflow: 'hidden',
  },
  // Under the name, past the icon (34 wide, plus the row's gap).
  catTrackIcon: { marginLeft: 42 },
  catMore: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  catMoreText: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.link },

  // day rows
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 64,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  dayMid: { flex: 1, minWidth: 0 },
  dayName: {
    fontFamily: theme.font.bodyBold,
    fontSize: 15,
    color: theme.colors.textPrimary,
  },
  daySub: {
    fontFamily: theme.font.body,
    fontSize: 13,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  dayAmt: { fontFamily: theme.font.monoBold, fontSize: 15, color: theme.colors.textPrimary },
  daySpinner: { paddingVertical: 24 },
  dayEmpty: { alignItems: 'center', paddingVertical: 8, gap: 4 },
  dayTotalRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  dayTotalLabel: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  dayTotalValue: { fontFamily: theme.font.monoBold, fontSize: 15, color: theme.colors.textPrimary },
});
