import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW, SECTION_TITLE, SECTION_GAP } from '@/constants/textStyles';

/** The even gap between Reports' blocks (heatmap card, day card, story cards, "Where it went"). */
export const BLOCK_GAP = 22;

// Shared by the Reports screen and its pieces (PeriodRow, ReportSummary, HeatmapCard, DayCard, StoryCards, CategoryBar, CategoryList, TrendChart, DayTotal).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  errTitle: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.expenseText },
  errDetail: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginTop: 4,
    textAlign: 'center',
  },
  empty: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textMuted, marginVertical: 16 },

  periodRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, marginBottom: 16 },
  periodPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.pill,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  periodArrow: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  // Shrinks and wraps rather than clipping a long custom range ("20 Dec 2025 – 4 Jan 2026").
  periodLabel: {
    flexShrink: 1,
    textAlign: 'center',
    fontFamily: theme.font.roundedBold,
    fontSize: 13,
    color: theme.colors.textPrimary,
  },
  gran: {
    flexDirection: 'row',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.pill,
    padding: 3,
  },
  granBtn: { paddingHorizontal: 9, paddingVertical: 8, borderRadius: theme.radius.pill },
  granBtnOn: { backgroundColor: theme.colors.secondaryTint },
  granText: { fontFamily: theme.font.bodyMedium, fontSize: 12, color: theme.colors.textMuted },
  granTextOn: { color: theme.colors.textPrimary },

  // Days / Categories / Trends, pinned under the summary. SegmentedControl
  // brings its own bottom margin; the negative one trims it to the gap this bar wants.
  tabs: { paddingHorizontal: 20, marginBottom: -6 },

  // The pinned summary: the period's total and its day figures, always in view.
  summary: { paddingHorizontal: 20, paddingBottom: 12, gap: 4 },
  summaryHead: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  summaryMain: { flex: 1, minWidth: 0 },
  summaryBig: {
    fontFamily: theme.font.monoBold,
    fontSize: 24,
    letterSpacing: -1,
    color: theme.colors.textPrimary,
  },

  eyebrow: EYEBROW,
  // Same red/green + arrow badge language This Month's KPI tiles and the
  // stat cards already use, instead of a small two-line corner label.
  vsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: theme.radius.pill,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  vsBadgeText: { fontFamily: theme.font.bodyBold, fontSize: 10.5 },

  // The Days tab's heatmap card.
  hmCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    padding: 14,
    gap: 10,
    marginBottom: BLOCK_GAP,
  },
  filterChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: '100%',
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
    paddingLeft: 10,
    paddingRight: 8,
    paddingVertical: 5,
  },
  filterChipText: {
    flexShrink: 1,
    fontFamily: theme.font.bodyBold,
    fontSize: 12,
    color: theme.colors.textPrimary,
  },
  hmFacts: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted },
  hmFactStrong: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  hmFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  hmHint: { flex: 1, fontFamily: theme.font.body, fontSize: 11.5, color: theme.colors.textSecondary },

  // Story cards: the period "in short", swiped sideways.
  storyBlock: { marginBottom: BLOCK_GAP },
  storyHead: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between' },
  storyPos: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted },
  story: {
    minHeight: 168,
    borderRadius: theme.radius.xl2,
    padding: 16,
    justifyContent: 'space-between',
    gap: 10,
  },
  storyCompact: { borderRadius: theme.radius.xl2, paddingHorizontal: 16, paddingVertical: 12, gap: 2 },
  storyCompactTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textPrimary },
  storyCompactDetail: {
    fontFamily: theme.font.body,
    fontSize: 12.5,
    lineHeight: 18,
    color: theme.colors.textSecondary,
  },
  storyKicker: {
    fontFamily: theme.font.monoBold,
    fontSize: 10.5,
    letterSpacing: 0.4,
    color: theme.colors.inkSoft,
  },
  storyBig: {
    fontFamily: theme.font.roundedBold,
    fontSize: 28,
    lineHeight: 32,
    color: theme.colors.textPrimary,
  },
  storyDetail: {
    fontFamily: theme.font.body,
    fontSize: 13.5,
    lineHeight: 19,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },
  storyCta: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textPrimary },
  storyFoot: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textSecondary },
  storyMoonRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  storyMoonText: { flex: 1, minWidth: 0 },
  storyDots: { flexDirection: 'row', justifyContent: 'center', gap: 5, marginTop: 10 },
  storyDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.colors.borderSoft },
  storyDotOn: { width: 16, backgroundColor: theme.colors.ink },

  // The day open under the heatmap.
  dayCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: BLOCK_GAP,
  },
  dayHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 14,
    paddingBottom: 8,
  },
  dayHeadText: { flex: 1, minWidth: 0 },
  dayTitle: { fontFamily: theme.font.roundedBold, fontSize: 15, color: theme.colors.textPrimary },
  dayClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceAlt,
  },
  dayFoot: {
    marginTop: 4,
    paddingTop: 10,
    paddingHorizontal: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },

  // Weekday rhythm: seven bars, a dashed "usual day" line, and a read line.
  rhythmBlock: { marginBottom: BLOCK_GAP },
  rhythmCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    padding: 14,
    gap: 10,
  },
  rhythmChart: { height: 128, flexDirection: 'row', alignItems: 'flex-end', gap: 6, paddingTop: 14 },
  rhythmBar: { flex: 1, height: '100%', justifyContent: 'flex-end', alignItems: 'center', gap: 4 },
  rhythmValue: {
    height: 12,
    fontFamily: theme.font.mono,
    fontSize: 9.5,
    color: theme.colors.textMuted,
  },
  rhythmValueOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  rhythmFill: { width: '100%', borderTopLeftRadius: 8, borderTopRightRadius: 8, borderRadius: 4 },
  rhythmLabel: { height: 14, fontFamily: theme.font.mono, fontSize: 10, color: theme.colors.textMuted },
  rhythmLabelOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  rhythmUsual: {
    position: 'absolute',
    left: 0,
    right: 0,
    borderTopWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.colors.textSecondary,
    opacity: 0.55,
  },
  rhythmUsualTag: {
    position: 'absolute',
    right: 0,
    bottom: 2,
    paddingHorizontal: 2,
    backgroundColor: theme.colors.surface,
    fontFamily: theme.font.mono,
    fontSize: 9,
    color: theme.colors.textSecondary,
  },
  rhythmRead: {
    fontFamily: theme.font.body,
    fontSize: 13,
    lineHeight: 18,
    color: theme.colors.textPrimary,
  },
  rhythmEmpty: {
    paddingVertical: 18,
    paddingHorizontal: 14,
    textAlign: 'center',
    fontFamily: theme.font.body,
    fontSize: 13,
    color: theme.colors.textMuted,
  },

  // Biggest spends: the period's largest single expenses, in the day card's row.
  bigBlock: { marginBottom: BLOCK_GAP },
  bigCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    paddingTop: 4,
    paddingBottom: 12,
    overflow: 'hidden',
  },
  bigFoot: {
    marginTop: 4,
    paddingTop: 10,
    paddingHorizontal: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  bigFootStrong: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  bigRowOn: { backgroundColor: theme.colors.surfaceAlt },

  // Categories: how the list is grouped (by category or by account).
  groupPill: { alignSelf: 'flex-start', marginBottom: 12 },
  catSplitCaption: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textMuted,
    paddingTop: 8,
  },

  // Trends: one line chart with a Spending / Net worth switch.
  trendCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    padding: 14,
    gap: 6,
  },
  trendHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  trendTitle: { fontFamily: theme.font.roundedBold, fontSize: 15, color: theme.colors.textPrimary },
  trendSwitch: {
    flexDirection: 'row',
    padding: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
  },
  trendSwitchBtn: { paddingHorizontal: 11, paddingVertical: 4, borderRadius: theme.radius.pill },
  trendSwitchBtnOn: { backgroundColor: theme.colors.ink },
  trendSwitchText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textSecondary },
  trendSwitchTextOn: { fontFamily: theme.font.bodyBold, color: theme.colors.surface },
  trendRead: {
    fontFamily: theme.font.body,
    fontSize: 12.5,
    lineHeight: 17,
    color: theme.colors.textSecondary,
  },

  trendBlock: { marginTop: BLOCK_GAP, gap: 12 },

  // Money in and out: paired bars per month with what was kept under each, then a three-cell summary.
  flowLegend: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  flowLegendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  flowLegendDot: { width: 10, height: 10, borderRadius: 3 },
  flowLegendText: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },
  flowChart: { flexDirection: 'row', alignItems: 'flex-end', gap: 2, paddingTop: 6 },
  flowCol: { flex: 1, alignItems: 'center', gap: 4, paddingTop: 6, paddingBottom: 4, borderRadius: 10 },
  flowColOn: { backgroundColor: theme.colors.inkWash },
  flowBars: { height: 100, flexDirection: 'row', alignItems: 'flex-end', gap: 2 },
  flowBar: { width: 10, borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  flowBarLive: { borderWidth: 1.5, borderStyle: 'dashed', borderColor: theme.colors.ink },
  flowLabel: { fontFamily: theme.font.mono, fontSize: 10, color: theme.colors.textMuted },
  flowLabelOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  flowKept: {
    minWidth: 34,
    alignItems: 'center',
    paddingVertical: 2,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.secondaryTint,
  },
  flowKeptNeg: { backgroundColor: theme.colors.idCoral },
  flowKeptLive: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: theme.colors.secondaryDeep,
  },
  flowKeptText: { fontFamily: theme.font.monoBold, fontSize: 9.5, color: theme.colors.incomeText },
  flowKeptTextNeg: { color: theme.colors.expenseText },
  flowKeptCaption: { ...EYEBROW, textAlign: 'center', marginTop: -2 },
  stripCard: {
    flexDirection: 'row',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  stripCell: { flex: 1, minWidth: 0, paddingHorizontal: 12, paddingVertical: 12, gap: 2 },
  stripCellDivided: { borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: theme.colors.borderSoft },
  stripLabel: { ...EYEBROW },
  stripValue: { fontFamily: theme.font.monoBold, fontSize: 13.5, color: theme.colors.textPrimary },
  stripSub: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },

  // Against your usual: each category's month beside its own earlier months.
  tracksBlock: { marginTop: BLOCK_GAP },
  tracksCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    overflow: 'hidden',
  },
  trackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 11,
    paddingHorizontal: 14,
    minHeight: 62,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  trackMid: { flex: 1, minWidth: 0 },
  trackName: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.textPrimary },
  trackSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 2 },
  trackEnd: { alignItems: 'flex-end', gap: 2 },
  trackPct: { fontFamily: theme.font.monoBold, fontSize: 11.5, color: theme.colors.textMuted },
  trackPctOver: { color: theme.colors.expenseText },
  trackPctUnder: { color: theme.colors.incomeText },
  trackFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  trackFootText: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted },
  trackFootLink: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textPrimary },
  tracksNote: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 8 },

  trendLink: { alignSelf: 'flex-start', paddingVertical: 4 },
  trendLinkText: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textPrimary },

  flowSwitch: { marginBottom: 12 },
  tidyNudge: {
    marginTop: 10,
    padding: 12,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.idGold,
  },
  tidyNudgeText: {
    fontFamily: theme.font.body,
    fontSize: 12.5,
    lineHeight: 18,
    color: theme.colors.textPrimary,
  },
  tidyNudgeLink: { fontFamily: theme.font.bodyBold, textDecorationLine: 'underline' },
  blockTitle: { ...SECTION_TITLE, marginBottom: SECTION_GAP.bottom },
  legend: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendText: { fontFamily: theme.font.body, fontSize: 10, color: theme.colors.textMuted },
  legendSwatch: { width: 11, height: 11, borderRadius: 3 },

  catCard: {
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderRadius: theme.radius.xl2,
    paddingHorizontal: 14,
    overflow: 'hidden',
  },
  catBar: {
    flexDirection: 'row',
    height: 14,
    gap: 2,
    marginBottom: 12,
    borderRadius: 7,
    overflow: 'hidden',
  },
  catBarSeg: { flexBasis: 0, minWidth: 2 },
  catRow: { paddingVertical: 10 },
  // The picked row: tinted edge to edge, the others fade.
  catRowOn: { marginHorizontal: -14, paddingHorizontal: 14, backgroundColor: theme.colors.surfaceAlt },
  catRowDim: { opacity: 0.45 },
  catPanel: {
    marginHorizontal: -14,
    paddingHorizontal: 14,
    paddingBottom: 10,
    gap: 6,
    backgroundColor: theme.colors.surfaceAlt,
  },
  catSplitLoading: { paddingVertical: 8 },
  catSplitRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingLeft: 14 },
  catSplitName: { flex: 1, fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textSecondary },
  catSplitAmt: { fontFamily: theme.font.mono, fontSize: 11.5, color: theme.colors.textPrimary },
  catLinks: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 16, rowGap: 2, paddingTop: 4 },
  catLink: { paddingVertical: 4 },
  catLinkText: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textPrimary },
  catTop: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  catName: { flex: 1, fontFamily: theme.font.bodyMedium, fontSize: 13, color: theme.colors.textPrimary },
  catDot: { width: 8, height: 8, borderRadius: 4 },
  catPct: {
    fontFamily: theme.font.mono,
    fontSize: 10,
    color: theme.colors.textMuted,
    width: 34,
    textAlign: 'right',
  },
  catRight: { flexDirection: 'row', alignItems: 'center', gap: 5, marginLeft: 8 },
  catAmt: { fontFamily: theme.font.monoBold, fontSize: 12, color: theme.colors.textPrimary },
  catDelta: { fontFamily: theme.font.mono, fontSize: 10 },
  catTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: theme.colors.inkWash,
    overflow: 'hidden',
  },
  catMore: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  catMoreText: { fontFamily: theme.font.bodyMedium, fontSize: 11.5, color: theme.colors.textMuted },

  // day rows
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  dayMid: { flex: 1, minWidth: 0 },
  dayName: {
    fontFamily: theme.font.bodyBold,
    fontSize: 12.5,
    color: theme.colors.textPrimary,
  },
  daySub: {
    fontFamily: theme.font.body,
    fontSize: 10,
    color: theme.colors.textMuted,
    marginTop: 1,
  },
  dayAmt: { fontFamily: theme.font.monoBold, fontSize: 12, color: theme.colors.textPrimary },
  daySpinner: { paddingVertical: 24 },
  dayEmpty: { alignItems: 'center', paddingVertical: 8, gap: 4 },
  dayTotalRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  dayTotalLabel: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
  },
  dayTotalValue: { fontFamily: theme.font.monoBold, fontSize: 13, color: theme.colors.textPrimary },
});
