import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Recurring screen, RuleCard and RuleModal.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  introText: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginHorizontal: 20,
    marginBottom: 16,
    lineHeight: 18,
  },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expense },
  errorDetail: { fontSize: 11.5, color: theme.colors.textSecondary, marginTop: 3, lineHeight: 16 },
  sectionDivider: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    color: theme.colors.textMuted,
    letterSpacing: 0.6,
    marginTop: 14,
    marginBottom: 6,
  },
  card: { marginBottom: 10, padding: 14 },
  cardMuted: { opacity: 0.6 },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardTitle: { fontSize: 15, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  cardSub: { fontSize: 11.5, color: theme.colors.textMuted, marginTop: 3 },
  cardAmount: { fontSize: 15, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: theme.border.thin,
    borderTopColor: theme.colors.borderSoft,
  },
  pauseLabel: { fontSize: 11.5, fontFamily: theme.font.bodyBold, color: theme.colors.textSecondary },
  income: { color: theme.colors.income },
  expense: { color: theme.colors.expense },
  fieldLabel: {
    fontSize: 13,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textSecondary,
    marginBottom: 6,
    marginTop: 4,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  dateFieldsRow: { flexDirection: 'row', gap: 10 },
  dateFieldInput: { flex: 1, textAlign: 'center' },
  endDateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  errorText: { color: theme.colors.expense, fontSize: 13, marginTop: 4, marginBottom: 12 },
  modalActions: { flexDirection: 'row', marginTop: 8 },
});
