import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Styles for the Add Historical (bulk backfill) screen.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  sectionTitle: {
    fontSize: 12,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  introText: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginHorizontal: 20,
    marginTop: 16,
    lineHeight: 18,
  },
  monthStrip: { paddingHorizontal: 20, gap: 8, paddingBottom: 4 },
  form: {
    marginHorizontal: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.border.thick,
    borderColor: theme.colors.ink,
    borderRadius: theme.radius.lg,
    padding: 14,
  },
  fieldLabel: {
    fontSize: 13,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  dayStrip: { gap: 8, paddingBottom: 14 },
  dayCell: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surface,
  },
  dayCellActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  dayCellText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textPrimary },
  dayCellTextActive: { color: theme.colors.white },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  errorText: { color: theme.colors.expense, fontSize: 13, marginBottom: 12 },
  hintText: { fontSize: 12, color: theme.colors.textMuted, marginBottom: 10, lineHeight: 17 },
  list: {
    marginHorizontal: 20,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.border.thick,
    borderColor: theme.colors.ink,
    borderRadius: theme.radius.lg,
    overflow: 'hidden',
  },
  pendingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
    gap: 10,
  },
  pendingContent: { flex: 1, minWidth: 0 },
  pendingLabel: { fontSize: 14, fontFamily: theme.font.bodyMedium, color: theme.colors.textPrimary },
  pendingNoteInline: { fontSize: 12.5, color: theme.colors.textSecondary, fontFamily: theme.font.bodyMedium },
  pendingSub: { fontSize: 11.5, color: theme.colors.textMuted, marginTop: 2 },
  pendingValue: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  removeBtn: { padding: 4 },
  removeText: { fontSize: 14, color: theme.colors.textMuted },
  income: { color: theme.colors.income },
  expense: { color: theme.colors.expense },
  footer: {
    borderTopWidth: theme.border.thick,
    borderColor: theme.colors.ink,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  footerTotals: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  footerLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
  },
  footerValue: {
    fontSize: 15,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textPrimary,
    marginTop: 2,
  },
});
