import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { SCREEN } from '@/components/screenStyles';

// Shared by the Plan tiles and Coming up.
const TILE_GAP = 8;
export const STRIP_BAR_AREA = 46;

export const styles = StyleSheet.create({
  group: { gap: TILE_GAP, marginHorizontal: SCREEN.gutter },
  groupFirst: { marginTop: TILE_GAP },
  tileRow: { flexDirection: 'row', gap: TILE_GAP },
  tile: {
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    padding: 14,
    gap: 4,
    overflow: 'hidden',
  },
  tileWide: {},
  tileHalf: { flex: 1, minHeight: 116 },
  savingTile: { backgroundColor: theme.colors.primaryTint, gap: 10 },
  kickerRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginBottom: 2 },
  kicker: {
    flexShrink: 1,
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
  },
  bigValue: { fontFamily: theme.font.monoBold, fontSize: 26, color: theme.colors.textPrimary },
  value: { fontFamily: theme.font.monoBold, fontSize: 19, color: theme.colors.textPrimary },
  valueNote: { fontFamily: theme.font.bodyMedium, fontSize: 12, color: theme.colors.textSecondary },
  overValue: { color: theme.colors.expenseText },
  incomeValue: { color: theme.colors.incomeText },
  tileTitle: { fontFamily: theme.font.roundedBold, fontSize: 16, color: theme.colors.textPrimary },
  tileSub: { fontFamily: theme.font.body, fontSize: 12, lineHeight: 16, color: theme.colors.textSecondary },

  strip: { flexDirection: 'row', gap: 3, marginTop: 8 },
  stripDay: { flex: 1, alignItems: 'center', gap: 4 },
  stripBarArea: { height: STRIP_BAR_AREA, width: '100%', justifyContent: 'flex-end' },
  stripBar: { width: '100%', borderRadius: 5, backgroundColor: theme.colors.surfaceAlt },
  stripBill: {
    backgroundColor: theme.colors.idGold,
    borderBottomWidth: 3,
    borderBottomColor: theme.colors.idGoldDeep,
  },
  stripEmi: {
    backgroundColor: theme.colors.idCoral,
    borderBottomWidth: 3,
    borderBottomColor: theme.colors.idCoralDeep,
  },
  stripNum: {
    minWidth: 18,
    paddingVertical: 1,
    borderRadius: theme.radius.pill,
    textAlign: 'center',
    fontFamily: theme.font.mono,
    fontSize: 10,
    color: theme.colors.textMuted,
  },
  stripNumOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  stripNumSelected: { backgroundColor: theme.colors.ink, color: theme.colors.surface },
  stripCaption: {
    fontFamily: theme.font.body,
    fontSize: 12,
    lineHeight: 16,
    color: theme.colors.textSecondary,
  },
  stripCaptionBold: { fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  stripJump: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingVertical: 2,
  },
  stripJumpText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textPrimary },

  ring: { position: 'absolute', right: 12, top: 12 },

  bars: { gap: 7, marginTop: 6 },
  barRow: { gap: 3 },
  barTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  barName: { flex: 1, fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textPrimary },
  barEnd: { fontFamily: theme.font.monoBold, fontSize: 11, color: theme.colors.textSecondary },
  track: {
    height: 5,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.inkWash,
    overflow: 'hidden',
  },
  trackFill: { height: '100%', borderRadius: theme.radius.pill, backgroundColor: theme.colors.secondary },

  sprouts: { flexDirection: 'row', gap: 2 },
  sproutMissed: { opacity: 0.45 },

  goals: { gap: 8 },
  whatIf: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  whatIfIcon: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: theme.colors.glass,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whatIfText: {
    fontFamily: theme.font.body,
    fontSize: 12.5,
    lineHeight: 17,
    color: theme.colors.textPrimary,
  },
  whatIfBold: { fontFamily: theme.font.bodyBold },
  cuts: { flexDirection: 'row', gap: 6, marginTop: 8 },
  cut: {
    paddingHorizontal: 11,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  cutActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  cutText: { fontFamily: theme.font.bodyBold, fontSize: 11.5, color: theme.colors.textPrimary },
  cutTextActive: { fontFamily: theme.font.bodyBold, color: theme.colors.surface },

  dayHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 4,
  },
  dayHeadText: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
  },
  dayHeadAmount: { fontFamily: theme.font.monoBold, fontSize: 12, color: theme.colors.textPrimary },
  payWrap: { alignItems: 'flex-end', gap: 5 },
  payBtn: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.ink,
  },
  payBtnText: { fontFamily: theme.font.roundedBold, fontSize: 11.5, color: theme.colors.surface },
  links: {
    flexDirection: 'row',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  linkCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  linkDivider: { borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: theme.colors.borderSoft },
  linkText: { fontFamily: theme.font.bodyMedium, fontSize: 13, color: theme.colors.textSecondary },
});
