import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { SCREEN } from '@/components/screenStyles';
import { SOFT_LIFT } from '@/components/SoftCard';

// Shared by the Plan tiles and Coming up.
const TILE_GAP = 10;
export const STRIP_BAR_AREA = 56;

export const styles = StyleSheet.create({
  group: { gap: TILE_GAP, marginHorizontal: SCREEN.gutter },
  groupFirst: { marginTop: 6 },
  tileRow: { flexDirection: 'row', gap: TILE_GAP },
  // Every tile is the same calm white card; what a tile is about shows in its icon badge, and good or bad
  // news in the colour of its figure, not in a tinted fill.
  tile: {
    backgroundColor: theme.colors.surface,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    padding: 16,
    gap: 6,
    overflow: 'hidden',
    shadowColor: theme.colors.ink,
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  // The 14-day tile leads the tab, lifted like Home's month card.
  tileHero: { borderRadius: 26, paddingTop: 18, ...SOFT_LIFT },
  tileWide: {},
  tileHalf: { flex: 1, minHeight: 132 },
  savingTile: { gap: 12 },
  kickerRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 2 },
  kickerBadge: { width: 28, height: 28, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  kicker: {
    flexShrink: 1,
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  heroHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  countChip: {
    minHeight: 26,
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
  },
  countChipText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textSecondary },
  bigValue: {
    fontFamily: theme.font.monoBold,
    fontSize: 34,
    lineHeight: 40,
    letterSpacing: -1.4,
    color: theme.colors.textPrimary,
    marginTop: 4,
  },
  value: {
    fontFamily: theme.font.monoBold,
    fontSize: 22,
    letterSpacing: -0.6,
    color: theme.colors.textPrimary,
  },
  valueNote: {
    fontFamily: theme.font.body,
    fontSize: 13,
    letterSpacing: 0,
    color: theme.colors.textSecondary,
  },
  overValue: { color: theme.colors.expenseText },
  incomeValue: { color: theme.colors.incomeText },
  tileTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  tileSub: { fontFamily: theme.font.body, fontSize: 13, lineHeight: 18, color: theme.colors.textSecondary },

  strip: { flexDirection: 'row', gap: 4, marginTop: 14 },
  stripDay: { flex: 1, alignItems: 'center', gap: 6 },
  stripBarArea: { height: STRIP_BAR_AREA, width: '100%', justifyContent: 'flex-end' },
  stripBar: { width: '100%', borderRadius: 6, backgroundColor: theme.colors.trayTrack },
  stripBill: { backgroundColor: theme.colors.slice.due },
  stripEmi: { backgroundColor: theme.colors.slice.spent },
  stripNum: {
    minWidth: 22,
    height: 22,
    lineHeight: 22,
    borderRadius: 11,
    overflow: 'hidden',
    textAlign: 'center',
    fontFamily: theme.font.mono,
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  stripNumOn: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  stripNumSelected: { backgroundColor: theme.colors.ink, color: theme.colors.surface },
  stripLegend: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 10 },
  stripLegendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  stripLegendDot: { width: 10, height: 10, borderRadius: 3 },
  stripLegendText: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textSecondary },
  stripFoot: {
    marginTop: 12,
    paddingTop: 12,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  stripCaption: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textSecondary,
  },
  stripCaptionBold: { fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  stripJump: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
  },
  stripJumpText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.link },

  ring: { position: 'absolute', right: 14, top: 14 },

  bars: { gap: 10, marginTop: 8 },
  barRow: { gap: 6 },
  barTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  barName: { flex: 1, fontFamily: theme.font.body, fontSize: 14, color: theme.colors.textPrimary },
  barEnd: { fontFamily: theme.font.monoBold, fontSize: 12, color: theme.colors.textSecondary },
  track: {
    height: 8,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.divider,
    overflow: 'hidden',
  },
  trackFill: { height: '100%', borderRadius: theme.radius.pill, backgroundColor: theme.colors.slice.saved },

  sprouts: { flexDirection: 'row', gap: 3 },
  sproutMissed: { opacity: 0.45 },

  goals: { gap: 10 },
  // What-if: a soft sky panel inside the goals card.
  whatIf: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: theme.colors.primaryTint,
  },
  whatIfIcon: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whatIfText: {
    fontFamily: theme.font.body,
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textPrimary,
  },
  whatIfBold: { fontFamily: theme.font.bodyBold },
  cuts: { flexDirection: 'row', gap: 8, marginTop: 12 },
  cut: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  cutActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  cutText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.textPrimary },
  cutTextActive: { fontFamily: theme.font.bodyBold, color: theme.colors.surface },

  dayHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 2,
  },
  dayHeadText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textMuted },
  dayHeadAmount: { fontFamily: theme.font.monoBold, fontSize: 13, color: theme.colors.textSecondary },
  payWrap: { alignItems: 'flex-end', gap: 6 },
  payBtn: {
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.ink,
  },
  payBtnText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.surface },
  links: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  linkCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  linkDivider: { borderLeftWidth: 1, borderLeftColor: theme.colors.divider },
  linkText: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.link },
});
