import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { SCREEN } from '@/components/screenStyles';
import { GLASS } from '@/components/Glass';

// Plan as "the road ahead": glass cards on Home's wallpaper. Shared by the runway, jars, debt path, goals,
// the people and streak tiles, and Coming up.
const GAP = 10;
/** The runway's drawing height, without the date row under it. */
export const RUNWAY_HEIGHT = 112;
/** A budget jar's inside height (its liquid fills this). */
export const JAR_HEIGHT = 92;

const figure = {
  fontFamily: theme.font.body,
  fontSize: theme.typeSize.title,
  letterSpacing: -0.5,
  color: theme.colors.textPrimary,
} as const;

export const styles = StyleSheet.create({
  card: { marginHorizontal: SCREEN.gutter, padding: SCREEN.cardPad, gap: 10 },
  cardFirst: { marginTop: theme.layout.screenTopGap },
  row: { flexDirection: 'row', gap: GAP, marginHorizontal: SCREEN.gutter },
  rowGap: { gap: GAP },

  head: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },

  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },

  bigRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, flexWrap: 'wrap' },
  bigValue: {
    fontFamily: theme.font.bodyLight,
    fontSize: theme.typeSize.hero,
    lineHeight: 42,
    letterSpacing: -1.2,
    color: theme.colors.textPrimary,
  },
  bigNote: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.textMuted },
  bigNothing: {
    fontFamily: theme.font.body,
    fontSize: 28,
    letterSpacing: -0.5,
    color: theme.colors.textPrimary,
  },

  /* ---------- Runway ---------- */
  runway: { height: RUNWAY_HEIGHT, marginTop: 4 },
  runwayAxis: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  runwayAxisText: { fontFamily: theme.font.bodyMedium, fontSize: 11, color: theme.colors.textMuted },
  runwayStart: {
    position: 'absolute',
    left: 0,
    top: 0,
    fontFamily: theme.font.bodyMedium,
    fontSize: 11,
    color: theme.colors.textMuted,
  },
  runwayLow: {
    position: 'absolute',
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    color: theme.colors.textSecondary,
  },
  pin: { position: 'absolute', width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  pinDot: { width: 13, height: 13, borderRadius: 7, borderWidth: 3, backgroundColor: theme.colors.surface },
  pinDotOn: { width: 18, height: 18, borderRadius: 9, borderWidth: 4 },
  foot: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    paddingTop: 10,
    gap: 6,
  },
  footText: { fontFamily: theme.font.body, fontSize: 14, lineHeight: 20, color: theme.colors.textSecondary },
  footBold: { fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  jump: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 4 },
  jumpText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.link },

  /* ---------- Budget jars ---------- */
  caption: { fontFamily: theme.font.body, fontSize: 14, lineHeight: 20, color: theme.colors.textSecondary },
  captionBad: { fontFamily: theme.font.bodyBold, color: theme.colors.expenseText },
  captionOk: { fontFamily: theme.font.bodyBold, color: theme.colors.incomeText },
  jars: { gap: 10, paddingTop: 16, paddingHorizontal: 16 },
  jarsScroll: { marginHorizontal: -16 },
  jar: { width: 64, alignItems: 'center', gap: 5 },
  jarBody: {
    width: 52,
    height: JAR_HEIGHT,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderWidth: 1.5,
    borderColor: GLASS.edge,
    justifyContent: 'flex-end',
    padding: 3,
  },
  jarEmpty: {
    borderStyle: 'dashed',
    borderColor: 'rgba(18,19,15,0.22)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jarLiquid: {
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  jarLiquidFull: { borderRadius: 15 },
  jarIcon: { position: 'absolute', top: 10, left: 0, right: 0, alignItems: 'center', zIndex: 1 },
  spillWrap: { position: 'absolute', top: -13, left: -12, right: -12, alignItems: 'center', zIndex: 2 },
  spill: {
    minHeight: 20,
    justifyContent: 'center',
    paddingHorizontal: 7,
    borderRadius: 10,
    backgroundColor: theme.colors.expense,
  },
  spillText: { fontFamily: theme.font.bodyBold, fontSize: 10.5, color: theme.colors.surface },
  jarName: {
    maxWidth: '100%',
    fontFamily: theme.font.bodyBold,
    fontSize: 12,
    color: theme.colors.textPrimary,
  },
  jarLeft: { maxWidth: '100%', fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },
  jarOver: { fontFamily: theme.font.bodyBold, color: theme.colors.expenseText },

  /* ---------- Debt path ---------- */
  pathValue: { ...figure },
  pathNote: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    letterSpacing: 0,
    color: theme.colors.textMuted,
  },
  lanes: { gap: 12, marginTop: 4 },
  lane: { gap: 7 },
  laneTop: { flexDirection: 'row', alignItems: 'baseline', gap: 6 },
  laneName: {
    flexShrink: 1,
    fontFamily: theme.font.bodyBold,
    fontSize: 13.5,
    color: theme.colors.textPrimary,
  },
  laneSub: { flexShrink: 1, fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted },
  laneTrack: { height: 16, justifyContent: 'center' },
  laneBar: { height: 8, borderRadius: 4 },
  laneEnd: {
    position: 'absolute',
    top: 0,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 3,
    backgroundColor: theme.colors.surface,
  },
  laneEndLabel: {
    position: 'absolute',
    top: 0,
    lineHeight: 16,
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    color: theme.colors.textSecondary,
  },
  axis: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(18,19,15,0.12)',
    borderStyle: 'dashed',
    paddingTop: 5,
  },
  axisText: { fontFamily: theme.font.bodyMedium, fontSize: 11, color: theme.colors.textMuted },
  axisEnd: { fontFamily: theme.font.bodyBold, color: theme.colors.incomeText },
  more: { fontFamily: theme.font.body, fontSize: 12.5, color: theme.colors.textMuted },

  /* ---------- Goals ---------- */
  goals: { gap: 10, paddingHorizontal: SCREEN.gutter },
  goal: { width: 136, height: 156, padding: 14, overflow: 'hidden' },
  goalFill: { position: 'absolute', left: 0, right: 0, bottom: 0, opacity: 0.5 },
  goalFillEdge: { position: 'absolute', left: 0, right: 0, top: 0, height: 2, opacity: 0.8 },
  goalPct: {
    fontFamily: theme.font.bodyLight,
    fontSize: 30,
    lineHeight: 34,
    letterSpacing: -1,
    color: theme.colors.textPrimary,
  },
  goalPctSign: { fontFamily: theme.font.body, fontSize: 14, letterSpacing: 0, color: theme.colors.textMuted },
  goalName: {
    marginTop: 'auto',
    fontFamily: theme.font.bodyBold,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  goalAmt: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textSecondary },
  goalOf: { color: theme.colors.textMuted },
  goalNew: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(18,19,15,0.22)',
    borderRadius: 24,
  },
  goalNewDisc: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GLASS.fillStrong,
  },
  goalNewText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textSecondary },
  title: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  sub: { fontFamily: theme.font.body, fontSize: 13, lineHeight: 18, color: theme.colors.textSecondary },

  whatIfQ: { fontFamily: theme.font.body, fontSize: 14, lineHeight: 20, color: theme.colors.textSecondary },
  whatIfBold: { fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  lever: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cuts: { flexDirection: 'row', gap: 6 },
  cut: {
    minHeight: 36,
    minWidth: 54,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  cutText: { fontFamily: theme.font.bodyBold, fontSize: 13.5, color: theme.colors.textPrimary },
  cutTextOn: { color: theme.colors.surface },
  gain: { flex: 1, alignItems: 'flex-end' },
  gainValue: {
    fontFamily: theme.font.body,
    fontSize: 20,
    letterSpacing: -0.4,
    color: theme.colors.incomeText,
  },
  gainNote: { fontFamily: theme.font.body, fontSize: 11.5, color: theme.colors.textMuted },
  openRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    paddingTop: 10,
  },
  openText: { fontFamily: theme.font.bodyMedium, fontSize: 13.5, color: theme.colors.link },

  /* ---------- Friends & streak ---------- */
  tile: { flex: 1, minWidth: 0, minHeight: 150, padding: 14, gap: 6 },
  tileWide: { flex: 1.25 },
  go: { position: 'absolute', top: 14, right: 14 },
  value: { ...figure },
  income: { color: theme.colors.incomeText },
  over: { color: theme.colors.expenseText },
  tileSub: { fontFamily: theme.font.body, fontSize: 12.5, lineHeight: 17, color: theme.colors.textMuted },
  people: { flexDirection: 'row', gap: 6, marginTop: 'auto', overflow: 'hidden' },
  person: { alignItems: 'center', gap: 3 },
  avatar: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.surface },
  personAmt: { fontFamily: theme.font.bodyBold, fontSize: 10, color: theme.colors.textSecondary },
  sprouts: { flexDirection: 'row', alignItems: 'flex-end', gap: 4, height: 34, marginTop: 'auto' },

  /* ---------- Coming up ---------- */
  list: { marginHorizontal: SCREEN.gutter, paddingTop: 4, overflow: 'hidden' },
  group: { paddingLeft: 36, paddingRight: 14 },
  rail: { position: 'absolute', left: 19, width: 2, backgroundColor: 'rgba(18,19,15,0.1)' },
  node: {
    position: 'absolute',
    left: 14,
    top: 14,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2.5,
    backgroundColor: theme.colors.surface,
  },
  dayHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 11 },
  dayHeadText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textSecondary },
  dayHeadAmount: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textMuted },
  dueRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 60 },
  dueIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  dueMid: { flex: 1, minWidth: 0 },
  dueTitle: { fontFamily: theme.font.bodyMedium, fontSize: 15, color: theme.colors.textPrimary },
  dueSub: { fontFamily: theme.font.body, fontSize: 12.5, color: theme.colors.textMuted, marginTop: 1 },
  dueSoon: { color: theme.colors.dueInk },
  dueUrgent: { color: theme.colors.expenseText },
  dueAmount: { fontFamily: theme.font.bodyMedium, fontSize: 15, color: theme.colors.textPrimary },
  payWrap: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  payBtn: { minHeight: 32, justifyContent: 'center', paddingHorizontal: 14, borderRadius: theme.radius.pill },
  payBtnText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.surface },
  emptyRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 64, paddingHorizontal: 14 },
  links: {
    flexDirection: 'row',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    marginTop: 6,
  },
  linkCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  linkDivider: { borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: theme.colors.borderSoft },
  linkText: { fontFamily: theme.font.bodyMedium, fontSize: 14, color: theme.colors.link },
});
