import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW } from '@/constants/textStyles';

// Shared by the Transactions screen and its modals/rows (MonthPickerModal,
// FilterModal, TransactionRow, TransactionDetailModal, AddTransactionModal).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expenseText },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },

  // Search is its own mode (see the screen's own comment) — this row
  // replaces the scope pills/week nav while it's active, in the same slot.
  searchBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    // Starts where the period row it stands in for starts.
    marginTop: theme.layout.screenTopGap,
    marginBottom: 14,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: theme.radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: theme.font.body,
    color: theme.colors.textPrimary,
    padding: 0,
  },
  searchCancel: { fontSize: 13, fontFamily: theme.font.roundedMedium, color: theme.colors.textSecondary },
  searchLoading: { paddingVertical: 40, alignItems: 'center' },

  weekNavBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  weekNavArrow: { fontSize: 18, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  weekNavArrowDisabled: { color: theme.colors.textMuted, opacity: 0.35 },

  // The Spent card (the Activity cleanup sign-off, option A): Spent on its
  // own with a change pill, Week/Month in the corner, the chart, a one-line
  // legend (or what the tapped bar cost), and Money in | Net as a strip.
  sumCard: {
    marginHorizontal: 20,
    marginTop: 12,
    padding: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    overflow: 'hidden',
  },
  sumKicker: EYEBROW,
  headlineAmt: {
    fontFamily: theme.font.monoBold,
    fontSize: 32,
    color: theme.colors.textPrimary,
    marginTop: 4,
    // Clear of the Week/Month switch in the corner.
    marginRight: 120,
  },
  changePill: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: theme.radius.pill,
  },
  changePillUp: { backgroundColor: theme.colors.expenseTint },
  changePillDown: { backgroundColor: theme.colors.incomeTint },
  changeText: { fontFamily: theme.font.bodyBold, fontSize: 11.5 },
  // Room above the tallest bar for the tapped bar's amount bubble.
  sumChart: { marginTop: 28 },
  sumStrip: {
    flexDirection: 'row',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  sumStripCell: { flex: 1, gap: 4 },
  sumStripCellRight: {
    paddingLeft: 14,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: theme.colors.borderSoft,
  },
  sumStripValue: { fontFamily: theme.font.monoBold, fontSize: 14, color: theme.colors.textPrimary },
  scopeSwitch: {
    position: 'absolute',
    top: 14,
    right: 14,
    zIndex: 1,
    flexDirection: 'row',
    padding: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
  },
  scopeBtn: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: theme.radius.pill },
  scopeBtnOn: { backgroundColor: theme.colors.ink },
  scopeText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textSecondary },
  scopeTextOn: { fontFamily: theme.font.bodyBold, color: theme.colors.surface },

  // ‹ This week › centred, its dates under it.
  periodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    marginTop: theme.layout.screenTopGap,
  },
  periodNav: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  periodNavOff: { opacity: 0.3 },
  periodTitleBtn: { flex: 1, alignItems: 'center' },
  periodTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  periodSub: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textMuted, marginTop: 1 },

  listArea: { flex: 1 },
  edgeFade: { position: 'absolute', top: 0, left: 0, right: 0, height: 14 },

  // Week scope's rail: one segment per week of the month, sized by its days.
  weekRail: { paddingHorizontal: 24, marginTop: 10 },
  weekRailBar: { flexDirection: 'row', gap: 4 },
  weekRailSeg: { height: 14, justifyContent: 'center' },
  weekRailFill: { height: 6, borderRadius: 3, backgroundColor: theme.colors.borderSoft },
  weekRailNow: {
    position: 'absolute',
    top: 0,
    alignSelf: 'center',
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: theme.colors.primary,
  },

  // The type filter as one segmented bar, then any picked categories and
  // accounts on their own line, only while there are some. The gap below
  // matches the gap between days.
  typeBar: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 14,
    padding: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  typeBtn: { flex: 1, alignItems: 'center', paddingVertical: 7, borderRadius: theme.radius.pill },
  typeBtnOn: { backgroundColor: theme.colors.ink },
  typeText: { fontFamily: theme.font.roundedMedium, fontSize: 12.5, color: theme.colors.textSecondary },
  typeTextOn: { color: theme.colors.surface },
  chipsRow: { gap: 6, paddingHorizontal: 20, paddingTop: 10 },
  filterGap: { height: 16 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  chipCat: { backgroundColor: theme.colors.primaryTint },
  chipText: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textSecondary },

  yearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    marginBottom: 16,
  },
  yearLabel: {
    fontSize: 17,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textPrimary,
    minWidth: 60,
    textAlign: 'center',
  },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  monthCell: {
    width: '30%',
    paddingVertical: 14,
    borderRadius: theme.radius.md,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
  },
  monthCellDisabled: { opacity: 0.35 },
  monthCellText: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  monthCellTextDisabled: { color: theme.colors.textMuted },
  rowNoteInline: { fontSize: 13, color: theme.colors.textSecondary, fontFamily: theme.font.body },
  income: { color: theme.colors.incomeText },
  expense: { color: theme.colors.expenseText },
  rowRefund: { fontFamily: theme.font.bodyBold, color: theme.colors.incomeText },
  // The Details / Actions switch under a transaction's card.
  detailTabs: { marginBottom: 12 },
  // A split part's detail: the whole payment, this part in bold.
  splitCard: {
    marginBottom: 12,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  splitCardTitle: { ...EYEBROW },
  splitPart: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  splitPartName: { flex: 1, fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textSecondary },
  splitPartAmount: { fontFamily: theme.font.mono, fontSize: 13, color: theme.colors.textSecondary },
  splitPartMine: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginBottom: 10,
    lineHeight: 17,
  },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  subGroup: {
    marginTop: -6,
    marginBottom: 14,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  subGroupLabel: {
    fontSize: 11.5,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
});
