import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW } from '@/constants/textStyles';
import { GLASS } from '@/components/Glass';

// Shared by the Transactions screen and its modals/rows (FilterModal, TransactionRow,
// TransactionDetailModal).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expenseText },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },

  // Search is its own mode (see the screen's own comment) — this row
  // replaces the period pill and the Week / Month switch in the header while it is active.
  searchBarRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 2, marginBottom: 4 },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: theme.radius.pill,
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: theme.font.body,
    color: theme.colors.textPrimary,
    padding: 0,
  },
  searchCancel: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.link },
  searchLoading: { paddingVertical: 40, alignItems: 'center' },

  // The Spent card leads the tab, frosted like Home's month card: the kicker, a big light figure, its chips
  // (the change, money in, net), the chart and a one-line legend.
  sumCard: { marginHorizontal: 20, marginTop: 8, padding: 16 },
  sumKicker: { fontFamily: theme.font.bodyMedium, fontSize: 13, color: theme.colors.textSecondary },
  headlineAmt: {
    fontFamily: theme.font.bodyLight,
    fontSize: 40,
    lineHeight: 46,
    letterSpacing: -1.4,
    color: theme.colors.textPrimary,
    marginTop: 6,
  },
  headlineSymbol: {
    fontFamily: theme.font.body,
    fontSize: 24,
    letterSpacing: 0,
    color: theme.colors.textMuted,
  },
  sumChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  sumChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 24,
    paddingHorizontal: 9,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(18,19,15,0.1)',
    maxWidth: '100%',
  },
  changePillUp: { borderColor: 'rgba(189,53,71,0.25)', backgroundColor: 'rgba(226,63,85,0.06)' },
  changePillDown: { borderColor: 'rgba(22,119,71,0.25)', backgroundColor: 'rgba(28,154,91,0.07)' },
  sumChipText: {
    flexShrink: 1,
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
  },
  // Room above the tallest bar for the tapped bar's amount bubble.
  sumChart: { marginTop: 22 },
  // Week | Month beside the period pill, the picked one on deep ink.
  scopeSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    height: 40,
    padding: 3,
    borderRadius: 20,
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  scopeBtn: { height: 32, justifyContent: 'center', paddingHorizontal: 11, borderRadius: 16 },
  scopeText: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textSecondary },
  scopeTextOn: { color: theme.colors.white },

  // ‹ This week › in a frosted pill, Week | Month beside it.
  periodBar: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 2 },
  periodRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 40,
    paddingHorizontal: 3,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  periodInner: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  periodNav: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  periodNavOff: { opacity: 0.35 },
  periodTitleBtn: { flex: 1, minWidth: 0, alignItems: 'center' },
  periodTitle: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.textPrimary },
  periodSub: { fontFamily: theme.font.body, fontSize: 11, color: theme.colors.textMuted },

  listArea: { flex: 1 },
  // The period, as a small chip in the shrunk header; it opens the month picker.
  periodChip: {
    height: 32,
    maxWidth: 130,
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
    justifyContent: 'center',
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  periodChipText: { fontFamily: theme.font.bodyBold, fontSize: 12, color: theme.colors.textPrimary },

  // Type filter as one segmented bar, then picked categories/accounts on their own line (only when some).
  // The gap below matches the gap between days.
  typeBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 16,
    height: 36,
    padding: 3,
    borderRadius: 18,
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  typeBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', height: 28, borderRadius: 14 },
  typeBtnOn: { backgroundColor: theme.colors.white, boxShadow: '0px 1px 4px rgba(16,32,51,0.12)' },
  typeText: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textSecondary },
  typeTextOn: { color: theme.colors.textPrimary },
  chipsRow: { gap: 8, paddingHorizontal: 20, paddingTop: 10 },
  filterGap: { height: 16 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 30,
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  chipText: { fontFamily: theme.font.bodyBold, fontSize: 12.5, color: theme.colors.textSecondary },

  rowNoteInline: { fontSize: 13, color: theme.colors.textSecondary, fontFamily: theme.font.body },
  income: { color: theme.colors.incomeText },
  expense: { color: theme.colors.expenseText },
  rowRefund: { fontFamily: theme.font.bodyBold, color: theme.colors.incomeText },
  // The Details / Actions switch under a transaction's card.
  detailTabs: { marginBottom: 12 },
  // A split part's detail: the whole payment, this part in bold.
  splitCard: {
    marginBottom: 12,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  splitCardTitle: { ...EYEBROW },
  splitPart: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  splitPartName: { flex: 1, fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textSecondary },
  splitPartAmount: { fontFamily: theme.font.mono, fontSize: 13, color: theme.colors.textSecondary },
  splitPartMine: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginBottom: 10,
    lineHeight: 17,
  },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  subGroup: {
    marginTop: -6,
    marginBottom: 14,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  subGroupLabel: {
    fontSize: 11.5,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
});
