import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW } from '@/constants/textStyles';
import { SOFT_LIFT } from '@/components/SoftCard';

/** The soft lift under white controls on the sky band (the period pill, the search box). */
const SKY_PILL_SHADOW = {
  shadowColor: theme.colors.link,
  shadowOpacity: 0.1,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 4 },
  elevation: 2,
} as const;

// Shared by the Transactions screen and its modals/rows (MonthPickerModal,
// FilterModal, TransactionRow, TransactionDetailModal, AddTransactionModal).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  errorBanner: {
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 14,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.expenseTint,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.expense,
  },
  errorTitle: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.expenseText },
  errorDetail: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textSecondary,
    marginTop: 3,
    lineHeight: 16,
  },

  // Search is its own mode (see the screen's own comment) — this row
  // replaces the period pill and week rail in the sky band while it's active.
  searchBarRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 2, marginBottom: 4 },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 16,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    ...SKY_PILL_SHADOW,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    fontFamily: theme.font.body,
    color: theme.colors.textPrimary,
    padding: 0,
  },
  searchCancel: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  searchLoading: { paddingVertical: 40, alignItems: 'center' },

  weekNavBtn: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  weekNavArrow: { fontSize: 18, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  weekNavArrowDisabled: { color: theme.colors.textMuted, opacity: 0.35 },

  // The Spent card leads the tab, lifted like Home's month card: a kicker with Week/Month beside it, the
  // figure and its change chip, the chart, a one-line legend, and Money in | Net as a strip.
  sumCard: {
    marginHorizontal: 20,
    marginTop: 6,
    padding: 18,
    paddingBottom: 16,
    backgroundColor: theme.colors.surface,
    borderRadius: 26,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    ...SOFT_LIFT,
  },
  sumHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  sumKickerRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexShrink: 1 },
  sumBadge: {
    width: 28,
    height: 28,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.idCoral,
  },
  sumKicker: {
    flexShrink: 1,
    fontFamily: theme.font.bodyMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  headlineAmt: {
    fontFamily: theme.font.monoBold,
    fontSize: 34,
    lineHeight: 40,
    letterSpacing: -1.4,
    color: theme.colors.textPrimary,
    marginTop: 10,
  },
  changePill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    minHeight: 28,
    marginTop: 8,
    paddingHorizontal: 11,
    borderRadius: theme.radius.pill,
  },
  changePillUp: { backgroundColor: theme.colors.expenseTint },
  changePillDown: { backgroundColor: theme.colors.incomeTint },
  changeText: { fontFamily: theme.font.bodyBold, fontSize: 13 },
  // Room above the tallest bar for the tapped bar's amount bubble.
  sumChart: { marginTop: 22 },
  sumStrip: {
    flexDirection: 'row',
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
  },
  sumStripCell: { flex: 1, gap: 3 },
  sumStripCellRight: { paddingLeft: 16, borderLeftWidth: 1, borderLeftColor: theme.colors.divider },
  sumStripLabel: { fontFamily: theme.font.bodyMedium, fontSize: 13, color: theme.colors.textSecondary },
  sumStripValue: { fontFamily: theme.font.monoBold, fontSize: 17, color: theme.colors.textPrimary },
  scopeSwitch: {
    flexDirection: 'row',
    padding: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceAlt,
  },
  scopeBtn: {
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderRadius: theme.radius.pill,
  },
  scopeBtnOn: { backgroundColor: theme.colors.ink },
  scopeText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textSecondary },
  scopeTextOn: { fontFamily: theme.font.bodyBold, color: theme.colors.surface },

  // ‹ This week › in a white pill on the sky band, its dates under it.
  periodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 52,
    marginTop: 2,
    paddingHorizontal: 6,
    borderRadius: 26,
    backgroundColor: theme.colors.surface,
    ...SKY_PILL_SHADOW,
  },
  periodNav: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primaryTint,
  },
  periodNavOff: { opacity: 0.35 },
  periodTitleBtn: { flex: 1, alignItems: 'center', paddingVertical: 4 },
  periodTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  periodSub: { fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textSecondary, marginTop: 1 },

  listArea: { flex: 1 },
  edgeFade: { position: 'absolute', top: 0, left: 0, right: 0, height: 14 },

  // Week scope's rail, on the sky band under the period pill: one segment per week of the month, sized by
  // its days.
  weekRail: { paddingHorizontal: 8, marginTop: 12 },
  weekRailBar: { flexDirection: 'row', gap: 5 },
  weekRailSeg: { height: 14, justifyContent: 'center' },
  weekRailFill: { height: 6, borderRadius: 3, backgroundColor: theme.colors.surface },
  weekRailNow: {
    position: 'absolute',
    top: 0,
    alignSelf: 'center',
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: theme.colors.link,
  },

  // Type filter as one segmented bar, then picked categories/accounts on their own line (only when some).
  // The gap below matches the gap between days.
  typeBar: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    padding: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  typeBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 36,
    borderRadius: theme.radius.pill,
  },
  typeBtnOn: { backgroundColor: theme.colors.ink },
  typeText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.textSecondary },
  typeTextOn: { color: theme.colors.surface },
  chipsRow: { gap: 8, paddingHorizontal: 20, paddingTop: 10 },
  filterGap: { height: 22 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  chipCat: { backgroundColor: theme.colors.primaryTint },
  chipText: { fontFamily: theme.font.bodyBold, fontSize: 13, color: theme.colors.textSecondary },

  yearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    marginBottom: 16,
  },
  yearLabel: {
    fontSize: 17,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textPrimary,
    minWidth: 60,
    textAlign: 'center',
  },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  monthCell: {
    width: '30%',
    paddingVertical: 14,
    borderRadius: theme.radius.md,
    borderWidth: theme.border.thin,
    borderColor: theme.colors.borderSoft,
    alignItems: 'center',
  },
  monthCellDisabled: { opacity: 0.35 },
  monthCellText: { fontSize: 14, fontFamily: theme.font.bodyBold, color: theme.colors.textPrimary },
  monthCellTextDisabled: { color: theme.colors.textMuted },
  rowNoteInline: { fontSize: 13, color: theme.colors.textSecondary, fontFamily: theme.font.body },
  income: { color: theme.colors.incomeText },
  expense: { color: theme.colors.expenseText },
  rowRefund: { fontFamily: theme.font.bodyBold, color: theme.colors.incomeText },
  // The Details / Actions switch under a transaction's card.
  detailTabs: { marginBottom: 12 },
  // A split part's detail: the whole payment, this part in bold.
  splitCard: {
    marginBottom: 12,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  splitCardTitle: { ...EYEBROW },
  splitPart: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  splitPartName: { flex: 1, fontFamily: theme.font.body, fontSize: 13, color: theme.colors.textSecondary },
  splitPartAmount: { fontFamily: theme.font.mono, fontSize: 13, color: theme.colors.textSecondary },
  splitPartMine: { fontFamily: theme.font.monoBold, color: theme.colors.textPrimary },
  hintText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    marginBottom: 10,
    lineHeight: 17,
  },
  fieldLabel: {
    fontSize: 10.5,
    fontFamily: theme.font.roundedMedium,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    marginBottom: 6,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  subGroup: {
    marginTop: -6,
    marginBottom: 14,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  subGroupLabel: {
    fontSize: 11.5,
    fontFamily: theme.font.bodyBold,
    color: theme.colors.textMuted,
    marginBottom: 8,
  },
});
