import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW } from '@/constants/textStyles';
import { GLASS } from '@/components/Glass';

// Shared by the Add screen (app/add-transaction.tsx) and its fields (AddFields.tsx).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  section: { marginBottom: 18 },
  // The category grid, a transfer's accounts and a friend's details each sit on one frosted card.
  fieldCard: { padding: 14 },
  // A friend entry's people: round avatars with an ink ring on the picked one.
  people: { gap: 10, paddingRight: 4 },
  person: { width: 60, alignItems: 'center', gap: 5 },
  avatarRing: { padding: 2, borderRadius: 28, borderWidth: 2, borderColor: 'transparent' },
  avatarRingOn: { borderColor: theme.colors.ink },
  avatar: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center' },
  avatarAdd: { borderWidth: 1.5, borderStyle: 'dashed', borderColor: theme.colors.borderSoft },
  avatarText: { fontFamily: theme.font.bodyBold, fontSize: 17, color: theme.colors.white },
  personName: { fontFamily: theme.font.bodyMedium, fontSize: 11.5, color: theme.colors.textSecondary },
  personNameOn: { color: theme.colors.textPrimary, fontFamily: theme.font.bodyBold },
  // A transfer: From and To as two cards, Swap in a dark disc between them.
  transfer: { gap: 8 },
  transferCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    borderRadius: 18,
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  transferIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  transferMid: { flex: 1, minWidth: 0 },
  transferLabel: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
  },
  transferName: { fontFamily: theme.font.bodyBold, fontSize: 15, color: theme.colors.textPrimary },
  transferBal: { fontFamily: theme.font.body, fontSize: 12.5, color: theme.colors.textMuted },
  swapBtn: {
    position: 'absolute',
    alignSelf: 'center',
    top: '50%',
    marginTop: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.ink,
    borderWidth: 3,
    borderColor: theme.colors.surface,
  },
  pickList: { gap: 8 },
  pickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 60,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  pickRowOn: { borderWidth: 2, borderColor: theme.colors.ink },
  pickSub: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    textTransform: 'capitalize',
  },
  label: {
    fontFamily: theme.font.roundedMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 8,
  },
  hint: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textMuted,
    lineHeight: 16,
    marginTop: 8,
  },

  // Amount is centred and large with no boxed input: the biggest number wins, as on Home's This Month card.
  heroLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 5,
    marginTop: 2,
    marginBottom: 6,
  },
  heroDot: { width: 6, height: 6, borderRadius: 3 },
  heroLabel: { fontFamily: theme.font.bodyBold, fontSize: 12.5 },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
    paddingVertical: 6,
  },
  amountCurrency: { fontFamily: theme.font.body, fontSize: 24, color: theme.colors.textMuted },
  amountText: {
    fontFamily: theme.font.bodyLight,
    fontSize: theme.typeSize.inputAmount,
    lineHeight: 52,
    letterSpacing: -1.5,
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  amountPlaceholder: { color: theme.colors.textMuted },
  // A blinking-free caret: shows the pad is typing into this amount.
  caret: { width: 2, height: 36, borderRadius: 1, backgroundColor: theme.colors.ink, marginLeft: 2 },
  expression: {
    fontFamily: theme.font.body,
    fontSize: 13,
    color: theme.colors.textMuted,
    textAlign: 'left',
    marginTop: -2,
  },

  // The amount on frosted glass, its label and currency in the entry type's colour.
  heroCard: {
    marginBottom: 14,
    padding: 16,
    borderRadius: 28,
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
    boxShadow: GLASS.shadow,
  },
  recentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 12 },
  recentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingLeft: 4,
    paddingRight: 11,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1.5,
    borderColor: GLASS.edge,
    maxWidth: '100%',
  },
  recentChipActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.ink },
  recentChipText: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  // Its own Text so a long category name is what gets cut at large text sizes, never the amount.
  recentChipAmount: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textPrimary,
    marginLeft: -2,
  },
  noAccountCard: { marginBottom: 18 },
  noAccountTitle: { fontFamily: theme.font.roundedBold, fontSize: 15, color: theme.colors.textPrimary },
  noAccountText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textSecondary,
    lineHeight: 17,
    marginTop: 4,
  },
  noAccountBtn: { marginTop: 12 },
  frequentRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', gap: 6, marginTop: 8 },
  frequentChip: {
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: theme.radius.pill,
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  frequentChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  frequentChipText: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textSecondary },
  frequentChipTextActive: { color: theme.colors.surface },

  noteInput: {
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: theme.colors.ink,
    borderRadius: 24,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 14,
    fontFamily: theme.font.body,
    color: theme.colors.textPrimary,
  },

  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: theme.radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  chipText: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textPrimary },

  addToList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderRadius: theme.radius.pill,
    minHeight: 52,
  },
  addToListText: { fontFamily: theme.font.bodyBold, fontSize: 14, color: theme.colors.textPrimary },

  // The entries queued with Add to list, on one frosted card.
  staged: {
    marginTop: 0,
    backgroundColor: GLASS.fill,
    borderWidth: 1,
    borderColor: GLASS.edge,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 4,
  },
  stagedHeadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  stagedHead: { ...EYEBROW, color: theme.colors.textSecondary },
  stagedHeadTotal: { fontFamily: theme.font.monoBold, fontSize: 12.5, color: theme.colors.textPrimary },
  stagedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 9,
  },
  stagedRowDivider: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.borderSoft },
  stagedMid: { flex: 1, minWidth: 0 },
  stagedLabel: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textPrimary },
  stagedNote: { fontFamily: theme.font.body, color: theme.colors.textMuted },
  stagedSub: { fontFamily: theme.font.body, fontSize: 10, color: theme.colors.textMuted, marginTop: 1 },
  stagedValue: { fontFamily: theme.font.monoBold, fontSize: 11.5, color: theme.colors.textPrimary },
  removeBtn: { padding: 2 },

  linkedNote: { marginBottom: 16 },
  // A white note card with a strip; the space at the top clears the strip.
  noteCard: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12 },
  linkedText: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textPrimary, lineHeight: 17 },

  // Frosted discs and pills on the wallpaper, like the other headers' buttons.
  trashBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },

  // The docked panel: detail chips, the pad and Save, on bright frosted glass.
  footer: {
    borderTopWidth: 1,
    borderTopColor: GLASS.edge,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: 'rgba(247,249,252,0.96)',
    paddingHorizontal: 12,
    paddingTop: 12,
    boxShadow: '0px -10px 30px rgba(16,32,51,0.08)',
  },
  saveBtn: { flex: 1 },
  actionRow: { flexDirection: 'row', gap: 8 },
  repeatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 36,
    paddingHorizontal: 14,
    borderRadius: theme.radius.pill,
    backgroundColor: GLASS.fillStrong,
    borderWidth: 1,
    borderColor: GLASS.edge,
  },
  repeatBtnText: { fontFamily: theme.font.bodyMedium, fontSize: 13, color: theme.colors.textPrimary },
  repeatNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: theme.colors.dueTint,
  },
  repeatNoteText: {
    flex: 1,
    fontFamily: theme.font.body,
    fontSize: 12.5,
    lineHeight: 17,
    color: theme.colors.dueInk,
  },
  // Bleeds to the screen's edges so it can slide sideways, while its first chip lines up with the pad.
  detailBar: { marginHorizontal: -12, marginBottom: 10, flexGrow: 0 },
  detailBarContent: { paddingHorizontal: 12, gap: 6 },
  detailChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 17,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  detailChipText: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 12.5,
    color: theme.colors.textPrimary,
    maxWidth: 150,
  },
  detailChipDisabled: { opacity: 0.4 },
  detailChipTextMuted: { color: theme.colors.textMuted },
  // A detail chip that's a switch (Money back), switched on.
  detailChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  detailChipTextActive: { color: theme.colors.surface },
  totalsRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 10 },
  total: { alignItems: 'center' },
  totalLabel: EYEBROW,
  totalValue: { fontFamily: theme.font.monoBold, fontSize: 12, marginTop: 2 },
  error: {
    fontFamily: theme.font.bodyBold,
    fontSize: 12,
    color: theme.colors.expenseText,
    textAlign: 'center',
    marginBottom: 8,
  },
  income: { color: theme.colors.incomeText },
  expense: { color: theme.colors.expenseText },
});
