import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { EYEBROW } from '@/constants/textStyles';

// Shared by the Add screen (app/add-transaction.tsx) and its fields (AddFields.tsx).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  section: { marginBottom: 18 },
  label: {
    fontFamily: theme.font.roundedMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 8,
  },
  hint: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textMuted,
    lineHeight: 16,
    marginTop: 8,
  },

  // Amount is centred and large with no boxed input: the biggest number wins, as on Home's This Month card.
  heroLabel: {
    ...EYEBROW,
    textAlign: 'center',
    marginBottom: 6,
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 6,
  },
  amountCurrency: { fontFamily: theme.font.monoBold, fontSize: 28, color: theme.colors.textMuted },
  amountText: {
    fontFamily: theme.font.monoBold,
    fontSize: 46,
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  amountPlaceholder: { color: theme.colors.textMuted },
  // A blinking-free caret: shows the pad is typing into this amount.
  caret: { width: 2, height: 36, borderRadius: 1, backgroundColor: theme.colors.ink, marginLeft: 2 },
  expression: {
    fontFamily: theme.font.mono,
    fontSize: 12.5,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginTop: -2,
  },

  heroCard: { marginBottom: 18 },
  recentRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 12 },
  recentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingLeft: 4,
    paddingRight: 11,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: 1.5,
    borderColor: 'transparent',
    maxWidth: '100%',
  },
  recentChipActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.secondary },
  recentChipText: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  // Its own Text so a long category name is what gets cut at large text sizes, never the amount.
  recentChipAmount: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textPrimary,
    marginLeft: -2,
  },
  noAccountCard: { marginBottom: 18 },
  noAccountTitle: { fontFamily: theme.font.roundedBold, fontSize: 15, color: theme.colors.textPrimary },
  noAccountText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textSecondary,
    lineHeight: 17,
    marginTop: 4,
  },
  noAccountBtn: { marginTop: 12 },
  frequentRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 7, marginTop: 4 },
  frequentChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.glass,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.inkHairline,
  },
  frequentChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  frequentChipText: { fontFamily: theme.font.monoBold, fontSize: 11, color: theme.colors.textPrimary },
  frequentChipTextActive: { color: theme.colors.surface },

  accountRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  accountTile: { width: 64, alignItems: 'center' },
  accountRing: { borderRadius: 28, borderWidth: 2, borderColor: 'transparent', padding: 2 },
  accountRingActive: { borderColor: theme.colors.ink },
  accountName: {
    fontFamily: theme.font.rounded,
    fontSize: 10.5,
    color: theme.colors.textSecondary,
    marginTop: 5,
    textAlign: 'center',
  },
  noteInput: {
    marginBottom: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: theme.font.body,
    color: theme.colors.textPrimary,
  },

  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: theme.radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  chipActive: { borderColor: theme.colors.secondary, backgroundColor: theme.colors.secondaryTint },
  chipText: { fontFamily: theme.font.bodyMedium, fontSize: 12, color: theme.colors.textPrimary },

  addToList: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.colors.secondary,
    borderRadius: theme.radius.pill,
    minHeight: 46,
  },
  addToListText: { fontFamily: theme.font.roundedBold, fontSize: 13, color: theme.colors.textPrimary },

  // One continuous "receipt" card: thick dashed top edge fakes a torn edge (RN has no clip-path); rows share
  // it with dashed dividers instead of per-row borders.
  staged: {
    marginTop: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderTopWidth: 3,
    borderTopColor: theme.colors.idCoralDeep,
    borderStyle: 'dashed',
    borderRadius: theme.radius.xl2,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 4,
  },
  stagedHeadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  stagedHead: { ...EYEBROW, color: theme.colors.textSecondary },
  stagedHeadTotal: { fontFamily: theme.font.monoBold, fontSize: 12.5, color: theme.colors.textPrimary },
  stagedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 9,
  },
  stagedRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    borderStyle: 'dashed',
  },
  stagedMid: { flex: 1, minWidth: 0 },
  stagedLabel: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textPrimary },
  stagedNote: { fontFamily: theme.font.body, color: theme.colors.textMuted },
  stagedSub: { fontFamily: theme.font.body, fontSize: 10, color: theme.colors.textMuted, marginTop: 1 },
  stagedValue: { fontFamily: theme.font.monoBold, fontSize: 11.5, color: theme.colors.textPrimary },
  removeBtn: { padding: 2 },

  linkedNote: { marginBottom: 16 },
  linkedText: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textPrimary, lineHeight: 17 },

  trashBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },

  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  saveBtn: { flex: 1 },
  actionRow: { flexDirection: 'row', gap: 8 },
  repeatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: theme.radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  repeatBtnText: { fontFamily: theme.font.roundedMedium, fontSize: 12.5, color: theme.colors.textPrimary },
  repeatNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: theme.colors.idGold,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.idGoldDeep,
  },
  repeatNoteText: {
    flex: 1,
    fontFamily: theme.font.body,
    fontSize: 12.5,
    lineHeight: 17,
    color: theme.colors.textPrimary,
  },
  // Bleeds to the screen's edges so it can slide sideways, while its first chip lines up with the pad.
  detailBar: { marginHorizontal: -20, marginBottom: 10, flexGrow: 0 },
  detailBarContent: { paddingHorizontal: 20, gap: 6 },
  detailChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceAlt,
  },
  detailChipText: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 12.5,
    color: theme.colors.textPrimary,
    maxWidth: 150,
  },
  detailChipDisabled: { opacity: 0.4 },
  detailChipTextMuted: { color: theme.colors.textMuted },
  // A detail chip that's a switch (Money back), switched on.
  detailChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  detailChipTextActive: { color: theme.colors.surface },
  totalsRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 10 },
  total: { alignItems: 'center' },
  totalLabel: EYEBROW,
  totalValue: { fontFamily: theme.font.monoBold, fontSize: 12, marginTop: 2 },
  error: {
    fontFamily: theme.font.bodyBold,
    fontSize: 12,
    color: theme.colors.expenseText,
    textAlign: 'center',
    marginBottom: 8,
  },
  income: { color: theme.colors.incomeText },
  expense: { color: theme.colors.expenseText },
});
