import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';

// Shared by the Add screen (app/add-transaction.tsx) and its fields (AddFields.tsx).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  section: { marginBottom: 18 },
  label: {
    fontFamily: theme.font.roundedMedium,
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 8,
  },
  hint: {
    fontFamily: theme.font.body,
    fontSize: 11.5,
    color: theme.colors.textMuted,
    lineHeight: 16,
    marginTop: 8,
  },

  // Amount is the one figure the whole transaction hangs on — centered and
  // large, no boxed input, the same "biggest number wins" treatment the
  // This Month card and stat tiles already use elsewhere on Home.
  heroLabel: {
    fontFamily: theme.font.bodyBold,
    fontSize: 11.5,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
    textAlign: 'center',
    marginBottom: 6,
  },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 6,
  },
  amountCurrency: { fontFamily: theme.font.monoBold, fontSize: 28, color: theme.colors.textMuted },
  amountInput: {
    fontFamily: theme.font.monoBold,
    fontSize: 46,
    color: theme.colors.textPrimary,
    minWidth: 60,
  },

  heroCard: { marginBottom: 18 },
  recentRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 7, marginTop: 6 },
  recentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingLeft: 4,
    paddingRight: 11,
    paddingVertical: 4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.glass,
    borderWidth: 1.5,
    borderColor: 'transparent',
    maxWidth: '100%',
  },
  recentChipActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.secondary },
  recentChipText: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 11.5,
    color: theme.colors.textPrimary,
    flexShrink: 1,
  },
  noAccountCard: { marginBottom: 18 },
  noAccountTitle: { fontFamily: theme.font.roundedBold, fontSize: 15, color: theme.colors.textPrimary },
  noAccountText: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textSecondary,
    lineHeight: 17,
    marginTop: 4,
  },
  noAccountBtn: { marginTop: 12 },
  frequentRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 7, marginTop: 4 },
  frequentChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.glass,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.inkHairline,
  },
  frequentChipActive: { backgroundColor: theme.colors.ink, borderColor: theme.colors.ink },
  frequentChipText: { fontFamily: theme.font.monoBold, fontSize: 11, color: theme.colors.textPrimary },
  frequentChipTextActive: { color: theme.colors.surface },

  accountRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  accountTile: { width: 64, alignItems: 'center' },
  accountRing: { borderRadius: 16, borderWidth: 2, borderColor: 'transparent', padding: 2 },
  accountRingActive: { borderColor: theme.colors.secondary },
  accountName: {
    fontFamily: theme.font.rounded,
    fontSize: 10.5,
    color: theme.colors.textSecondary,
    marginTop: 5,
    textAlign: 'center',
  },
  noteInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: theme.font.body,
    color: theme.colors.textPrimary,
  },

  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: theme.radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },
  chipActive: { borderColor: theme.colors.secondary, backgroundColor: theme.colors.secondaryTint },
  chipText: { fontFamily: theme.font.bodyMedium, fontSize: 12, color: theme.colors.textPrimary },

  addToList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.colors.secondary,
    borderRadius: 13,
    paddingVertical: 12,
    marginTop: 2,
  },
  addToListText: { fontFamily: theme.font.roundedBold, fontSize: 13, color: theme.colors.textPrimary },

  // Redrawn as one continuous "receipt" rather than a stack of bordered
  // mini-cards — a thicker dashed top edge stands in for a torn paper edge
  // (React Native has no CSS clip-path for the literal zigzag), and rows
  // inside share one card with dashed dividers between them instead of
  // each getting its own border.
  staged: {
    marginTop: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    borderTopWidth: 3,
    borderTopColor: theme.colors.idCoralDeep,
    borderStyle: 'dashed',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 4,
  },
  stagedHeadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  stagedHead: {
    fontFamily: theme.font.roundedBold,
    fontSize: 11,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textSecondary,
  },
  stagedHeadTotal: { fontFamily: theme.font.monoBold, fontSize: 12.5, color: theme.colors.textPrimary },
  stagedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 9,
  },
  stagedRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    borderStyle: 'dashed',
  },
  stagedMid: { flex: 1, minWidth: 0 },
  stagedLabel: { fontFamily: theme.font.bodyMedium, fontSize: 12.5, color: theme.colors.textPrimary },
  stagedNote: { fontFamily: theme.font.body, color: theme.colors.textMuted },
  stagedSub: { fontFamily: theme.font.body, fontSize: 10, color: theme.colors.textMuted, marginTop: 1 },
  stagedValue: { fontFamily: theme.font.monoBold, fontSize: 11.5, color: theme.colors.textPrimary },
  removeBtn: { padding: 2 },

  linkedNote: { marginBottom: 16 },
  linkedText: { fontFamily: theme.font.body, fontSize: 12, color: theme.colors.textPrimary, lineHeight: 17 },

  trashBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
  },

  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  totalsRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 10 },
  total: { alignItems: 'center' },
  totalLabel: {
    fontFamily: theme.font.mono,
    fontSize: 8.5,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: theme.colors.textMuted,
  },
  totalValue: { fontFamily: theme.font.monoBold, fontSize: 12, marginTop: 2 },
  error: {
    fontFamily: theme.font.bodyBold,
    fontSize: 12,
    color: theme.colors.expense,
    textAlign: 'center',
    marginBottom: 8,
  },
  income: { color: theme.colors.income },
  expense: { color: theme.colors.expense },
});
