import { StyleSheet } from 'react-native';
import { theme } from '@/constants/theme';
import { SECTION_TITLE, SECTION_GAP, EYEBROW } from '@/constants/textStyles';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  sectionTitle: {
    ...SECTION_TITLE,
    marginHorizontal: 20,
    marginTop: SECTION_GAP.top,
    marginBottom: SECTION_GAP.bottom,
  },
  statusCard: { marginTop: theme.layout.screenTopGap, padding: 16 },
  statusHead: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  statusTitle: { fontFamily: theme.font.roundedBold, fontSize: 17, color: theme.colors.textPrimary },
  errorLine: { color: theme.colors.expenseText },
  mainAction: { marginTop: 14 },
  scheduleBlock: {
    marginTop: 16,
    paddingTop: 14,
    gap: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.borderSoft,
  },
  eyebrow: { ...EYEBROW },
  scheduleFoot: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  scheduleHint: {
    flex: 1,
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    lineHeight: 17,
  },
  link: {
    fontFamily: theme.font.bodyMedium,
    fontSize: 12,
    color: theme.colors.textSecondary,
    textDecorationLine: 'underline',
  },
  linkDisabled: { opacity: 0.45 },
  tabs: { marginHorizontal: 20, marginTop: 16 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    paddingRight: 20,
  },
  seeAll: { fontFamily: theme.font.bodyMedium, fontSize: 12, color: theme.colors.textSecondary },
  timeline: { overflow: 'hidden' },
  whenRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  latestChip: {
    paddingHorizontal: 7,
    paddingVertical: 1,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.primaryTint,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderSoft,
  },
  latestText: {
    fontFamily: theme.font.bodyBold,
    fontSize: 10,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: theme.colors.textSecondary,
  },
  copySub: { color: theme.colors.textSecondary },
  emptyCard: { padding: 16, alignItems: 'center' },
  emptyAfter: { marginTop: 12 },
  emptyTitle: { fontFamily: theme.font.roundedBold, fontSize: 16, color: theme.colors.textPrimary },
  emptySub: {
    fontFamily: theme.font.body,
    fontSize: 13,
    color: theme.colors.textSecondary,
    lineHeight: 19,
    marginTop: 4,
    textAlign: 'center',
  },
  restoreFile: { marginTop: 12 },
  copyHint: {
    fontFamily: theme.font.body,
    fontSize: 12,
    color: theme.colors.textMuted,
    lineHeight: 17,
    marginHorizontal: 20,
    marginTop: 10,
  },
  node: { paddingLeft: 40 },
  nodeCopy: { backgroundColor: theme.colors.idTeal },
  rail: { position: 'absolute', left: 22, width: 2, backgroundColor: theme.colors.borderSoft },
  dot: {
    position: 'absolute',
    left: 17,
    top: '50%',
    marginTop: -6,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: theme.colors.textMuted,
    backgroundColor: theme.colors.surface,
  },
  dotLatest: { backgroundColor: theme.colors.income, borderColor: theme.colors.income },
  dotCopy: { backgroundColor: theme.colors.idTeal, borderColor: theme.colors.income },
});
